/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 */
package com.app.mpadmin.domain;

import java.io.*;
import java.util.*;

import static org.junit.Assert.*;
import org.junit.Test;

import com.app.mpadmin.util.*;
import static org.hibernate.annotations.CacheConcurrencyStrategy.NONSTRICT_READ_WRITE;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.apache.log4j.Logger;
import org.hibernate.annotations.Cache;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Basic tests for AuthPermission
 */
@SuppressWarnings("unused")
public class AuthPermissionTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        AuthPermission model = new AuthPermission();
        assertFalse(model.isIdSet());
    }

    @Test
    public void isIdSetReturnsTrue() {
        AuthPermission model = new AuthPermission();
        model.setId(ValueGenerator.getUniqueInteger());
        assertNotNull(model.getId());
        assertTrue(model.isIdSet());
    }

    // test columns methods

    @Test
    public void toStringNotNull() {
        AuthPermission model = new AuthPermission();
        assertNotNull(model.toString());
    }

    @Test
    public void equalsUsingBusinessKey() {
        AuthPermission model1 = new AuthPermission();
        AuthPermission model2 = new AuthPermission();
        Integer contentTypeId = 1;
        model1.setContentTypeId(contentTypeId);
        model2.setContentTypeId(contentTypeId);
        String codename = "a";
        model1.setCodename(codename);
        model2.setCodename(codename);
        assertTrue(model1.equals(model2));
        assertTrue(model2.equals(model1));
        assertTrue(model1.hashCode() == model2.hashCode());
    }
}