/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 */
package com.app.mpadmin.domain;

import java.io.*;
import java.util.*;

import static org.junit.Assert.*;
import org.junit.Test;

import com.app.mpadmin.util.*;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;
import static javax.persistence.TemporalType.TIMESTAMP;
import static org.hibernate.annotations.CacheConcurrencyStrategy.NONSTRICT_READ_WRITE;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import javax.validation.constraints.Size;
import org.apache.log4j.Logger;
import org.hibernate.annotations.Cache;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;
import com.app.mpadmin.domain.TdRole;

/**
 * Basic tests for TdUserAuth
 */
@SuppressWarnings("unused")
public class TdUserAuthTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        TdUserAuth model = new TdUserAuth();
        assertFalse(model.isIdSet());
    }

    @Test
    public void isIdSetReturnsTrue() {
        TdUserAuth model = new TdUserAuth();
        model.setUserId(ValueGenerator.getUniqueInteger());
        assertNotNull(model.getUserId());
        assertTrue(model.isIdSet());
    }

    // test columns methods

    //-------------------------------------------------------------
    // Many to One:  TdUserAuth.roleId ==> TdRole.roleId
    //-------------------------------------------------------------

    @Test
    public void manyToOne_setRole() {
        TdUserAuth many = new TdUserAuth();

        // init
        TdRole one = new TdRole();

        one.setRoleId(ValueGenerator.getUniqueInteger());
        many.setRole(one);

        // make sure it is propagated properly
        assertNotNull(many.getRoleId());
        assertEquals(one, many.getRole());
        assertSame(many.getRoleId(), one.getRoleId());
        // now set it to back to null
        many.setRole(null);

        // make sure null is propagated properly
        assertNull(many.getRole());

        // make sure it is propagated on fk column as well
        assertNull(many.getRoleId());
    }

    @Test
    public void toStringNotNull() {
        TdUserAuth model = new TdUserAuth();
        assertNotNull(model.toString());
    }

    @Test
    public void equalsUsingPk() {
        TdUserAuth model1 = new TdUserAuth();
        TdUserAuth model2 = new TdUserAuth();

        Integer userId = ValueGenerator.getUniqueInteger();
        model1.setUserId(userId);
        model2.setUserId(userId);

        model1.setUsername("a");
        model2.setUsername("a");

        model1.setEmail("dummy@dummy.com");
        model2.setEmail("dummy@dummy.com");

        model1.setUserpassword("a");
        model2.setUserpassword("a");

        model1.setIsActive(1);
        model2.setIsActive(1);

        model1.setCreationDate(new Date());
        model2.setCreationDate(new Date());

        model1.setUpdationDate(new Date());
        model2.setUpdationDate(new Date());
        assertTrue(model1.isIdSet());
        assertTrue(model2.isIdSet());
        assertTrue(model1.hashCode() == model2.hashCode());
        assertTrue(model1.equals(model2));
        assertTrue(model2.equals(model1));
    }
}