/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.app.mpadmin.repository;

import java.util.Date;
import javax.inject.Named;
import javax.inject.Singleton;
import com.app.mpadmin.domain.AuthUser;
import com.app.mpadmin.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@SuppressWarnings("unused")
@Named
@Singleton
public class AuthUserGenerator {

    /**
     * Returns a new AuthUser instance filled with random values.
     */
    public AuthUser getAuthUser() {
        AuthUser authUser = new AuthUser();

        // simple attributes follows
        authUser.setUsername(ValueGenerator.getUniqueString(30));
        authUser.setFirstName("a");
        authUser.setLastName("a");
        authUser.setEmail("dummy@dummy.com");
        authUser.setPassword("a");
        authUser.setIsStaff(true);
        authUser.setIsActive(true);
        authUser.setIsSuperuser(true);
        authUser.setLastLogin(new Date());
        authUser.setDateJoined(new Date());
        return authUser;
    }

}