/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ServiceImplTest.e.vm.java
 */
package com.app.mpadmin.repository;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Before;
import org.junit.Test;

import com.app.mpadmin.domain.AuthMessage;
import com.app.mpadmin.repository.AuthMessageRepositoryImpl;
import com.app.mpadmin.dao.AuthMessageDao;
import com.app.mpadmin.dao.support.SearchParameters;

/**
 * Unit test on AuthMessageRepositoryImpl
 */
public class AuthMessageRepositoryImplTest {

    private AuthMessageRepositoryImpl authMessageRepositoryImpl;
    private AuthMessageDao authMessageDao;

    @Before
    public void setUp() {
        // called before each test.
        authMessageRepositoryImpl = new AuthMessageRepositoryImpl();
        authMessageDao = mock(AuthMessageDao.class);
        authMessageRepositoryImpl.setAuthMessageDao(authMessageDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        AuthMessage none = null;

        when(authMessageDao.findUniqueOrNone(any(AuthMessage.class), any(SearchParameters.class))).thenReturn(none);

        AuthMessage result = authMessageRepositoryImpl.findUniqueOrNone(new AuthMessage());

        assertThat(result).isNull();
        verify(authMessageDao, times(1)).findUniqueOrNone(any(AuthMessage.class), any(SearchParameters.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        AuthMessage unique = new AuthMessage();

        when(authMessageDao.findUniqueOrNone(any(AuthMessage.class), any(SearchParameters.class))).thenReturn(unique);

        AuthMessage result = authMessageRepositoryImpl.findUniqueOrNone(new AuthMessage());

        assertThat(result).isNotNull();
        verify(authMessageDao, times(1)).findUniqueOrNone(any(AuthMessage.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        when(authMessageDao.findUniqueOrNone(any(AuthMessage.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        authMessageRepositoryImpl.findUniqueOrNone(new AuthMessage());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void testFindUniqueCaseNone() {
        when(authMessageDao.findUnique(any(AuthMessage.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        authMessageRepositoryImpl.findUnique(new AuthMessage());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        AuthMessage unique = new AuthMessage();

        when(authMessageDao.findUnique(any(AuthMessage.class), any(SearchParameters.class))).thenReturn(unique);

        AuthMessage result = authMessageRepositoryImpl.findUnique(new AuthMessage());

        assertThat(result).isNotNull();
        verify(authMessageDao, times(1)).findUnique(any(AuthMessage.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueCaseMultiple() {
        when(authMessageDao.findUnique(any(AuthMessage.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        authMessageRepositoryImpl.findUnique(new AuthMessage());
    }
}