/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ServiceImplTest.e.vm.java
 */
package com.app.mpadmin.repository;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Before;
import org.junit.Test;

import com.app.mpadmin.domain.AuthUser;
import com.app.mpadmin.repository.AuthUserRepositoryImpl;
import com.app.mpadmin.dao.AuthUserDao;
import com.app.mpadmin.dao.support.SearchParameters;

/**
 * Unit test on AuthUserRepositoryImpl
 */
public class AuthUserRepositoryImplTest {

    private AuthUserRepositoryImpl authUserRepositoryImpl;
    private AuthUserDao authUserDao;

    @Before
    public void setUp() {
        // called before each test.
        authUserRepositoryImpl = new AuthUserRepositoryImpl();
        authUserDao = mock(AuthUserDao.class);
        authUserRepositoryImpl.setAuthUserDao(authUserDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        AuthUser none = null;

        when(authUserDao.findUniqueOrNone(any(AuthUser.class), any(SearchParameters.class))).thenReturn(none);

        AuthUser result = authUserRepositoryImpl.findUniqueOrNone(new AuthUser());

        assertThat(result).isNull();
        verify(authUserDao, times(1)).findUniqueOrNone(any(AuthUser.class), any(SearchParameters.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        AuthUser unique = new AuthUser();

        when(authUserDao.findUniqueOrNone(any(AuthUser.class), any(SearchParameters.class))).thenReturn(unique);

        AuthUser result = authUserRepositoryImpl.findUniqueOrNone(new AuthUser());

        assertThat(result).isNotNull();
        verify(authUserDao, times(1)).findUniqueOrNone(any(AuthUser.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        when(authUserDao.findUniqueOrNone(any(AuthUser.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        authUserRepositoryImpl.findUniqueOrNone(new AuthUser());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void testFindUniqueCaseNone() {
        when(authUserDao.findUnique(any(AuthUser.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        authUserRepositoryImpl.findUnique(new AuthUser());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        AuthUser unique = new AuthUser();

        when(authUserDao.findUnique(any(AuthUser.class), any(SearchParameters.class))).thenReturn(unique);

        AuthUser result = authUserRepositoryImpl.findUnique(new AuthUser());

        assertThat(result).isNotNull();
        verify(authUserDao, times(1)).findUnique(any(AuthUser.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueCaseMultiple() {
        when(authUserDao.findUnique(any(AuthUser.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        authUserRepositoryImpl.findUnique(new AuthUser());
    }
}