/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.app.mpadmin.repository;

import java.util.Date;
import javax.inject.Named;
import javax.inject.Singleton;
import com.app.mpadmin.domain.TdMakeSubmodel;
import com.app.mpadmin.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@SuppressWarnings("unused")
@Named
@Singleton
public class TdMakeSubmodelGenerator {

    /**
     * Returns a new TdMakeSubmodel instance filled with random values.
     */
    public TdMakeSubmodel getTdMakeSubmodel() {
        TdMakeSubmodel tdMakeSubmodel = new TdMakeSubmodel();

        // primary key column must be set manually
        tdMakeSubmodel.setMakeSubmodelId(ValueGenerator.getUniqueDouble());
        // simple attributes follows
        tdMakeSubmodel.setMakeModelId(1d);
        tdMakeSubmodel.setMakesubmodelDisplayName("a");
        tdMakeSubmodel.setMakesubmodelTechnicalName("a");
        tdMakeSubmodel.setMakesubmodelAlternateName("a");
        tdMakeSubmodel.setShortDesc("a");
        tdMakeSubmodel.setLongDesc("d".getBytes());
        tdMakeSubmodel.setSubmodelLaunchYear(1);
        tdMakeSubmodel.setFuelType(1);
        tdMakeSubmodel.setTransmissionType(1);
        tdMakeSubmodel.setWheeldriveType(1);
        tdMakeSubmodel.setEngineCapacity(1);
        tdMakeSubmodel.setBodyType(1);
        tdMakeSubmodel.setDoorCount(1);
        tdMakeSubmodel.setGearCount(1);
        tdMakeSubmodel.setFuelDelivery(1);
        tdMakeSubmodel.setValvesCount(1);
        tdMakeSubmodel.setIsActive(1);
        tdMakeSubmodel.setBhp(1);
        tdMakeSubmodel.setTorque(1);
        tdMakeSubmodel.setSubmodelType(1);
        tdMakeSubmodel.setSpecialEditionName("a");
        tdMakeSubmodel.setSpecialEditionInfo("a");
        tdMakeSubmodel.setSpecialEditionYear(1);
        tdMakeSubmodel.setMakesubmodelStatus(1);
        tdMakeSubmodel.setSeoResources("a");
        tdMakeSubmodel.setSeoUrl("http://www.jaxio.com");
        tdMakeSubmodel.setSeoH1("a");
        tdMakeSubmodel.setSeoH2("a");
        tdMakeSubmodel.setMetaTitle("a");
        tdMakeSubmodel.setMetaKeyword("a");
        tdMakeSubmodel.setMetaDescription("a");
        tdMakeSubmodel.setCustom1("a");
        tdMakeSubmodel.setCustom2("a");
        tdMakeSubmodel.setCustom3("a");
        tdMakeSubmodel.setCreationDate(new Date());
        tdMakeSubmodel.setUpdationDate(new Date());
        return tdMakeSubmodel;
    }

}