/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.app.mpadmin.repository;

import java.util.Date;
import javax.inject.Named;
import javax.inject.Singleton;
import com.app.mpadmin.domain.TdMakeModel;
import com.app.mpadmin.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@SuppressWarnings("unused")
@Named
@Singleton
public class TdMakeModelGenerator {

    /**
     * Returns a new TdMakeModel instance filled with random values.
     */
    public TdMakeModel getTdMakeModel() {
        TdMakeModel tdMakeModel = new TdMakeModel();

        // primary key column must be set manually
        tdMakeModel.setMakeModelId(ValueGenerator.getUniqueInteger());
        // simple attributes follows
        //tdMakeModel.setMakeId(1);
        tdMakeModel.setMakemodelDisplayName("a");
        tdMakeModel.setMakemodelTechnicalName("a");
        tdMakeModel.setMakemodelAlternateName("a");
        tdMakeModel.setShortDesc("a");
        tdMakeModel.setLongDesc("d".getBytes());
        tdMakeModel.setIsActive(1);
        tdMakeModel.setModelLaunchYear(1);
        tdMakeModel.setFuelType(1);
        tdMakeModel.setTransmissionType(1);
        tdMakeModel.setWheeldriveType(1);
        tdMakeModel.setEngineCapacity(1);
        tdMakeModel.setBodyType(1);
        tdMakeModel.setDoorCount(1);
        tdMakeModel.setGearCount(1);
        tdMakeModel.setFuelDelivery(1);
        tdMakeModel.setValvesCount(1);
        tdMakeModel.setBhp(1);
        tdMakeModel.setTorque(1);
        tdMakeModel.setMakemodelStatus(1);
        tdMakeModel.setSeoResources("a");
        tdMakeModel.setSeoUrl("http://www.jaxio.com");
        tdMakeModel.setSeoH1("a");
        tdMakeModel.setSeoH2("a");
        tdMakeModel.setMetaTitle("a");
        tdMakeModel.setMetaKeyword("a");
        tdMakeModel.setMetaDescription("a");
        tdMakeModel.setCustom1("a");
        tdMakeModel.setCustom2("a");
        tdMakeModel.setCustom3("a");
        tdMakeModel.setCreationDate(new Date());
        tdMakeModel.setUpdationDate(new Date());
        return tdMakeModel;
    }

}