/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ServiceImplTest.e.vm.java
 */
package com.app.mpadmin.repository;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Before;
import org.junit.Test;

import com.app.mpadmin.domain.TdMetro;
import com.app.mpadmin.repository.TdMetroRepositoryImpl;
import com.app.mpadmin.dao.TdMetroDao;
import com.app.mpadmin.dao.support.SearchParameters;

/**
 * Unit test on TdMetroRepositoryImpl
 */
public class TdMetroRepositoryImplTest {

    private TdMetroRepositoryImpl tdMetroRepositoryImpl;
    private TdMetroDao tdMetroDao;

    @Before
    public void setUp() {
        // called before each test.
        tdMetroRepositoryImpl = new TdMetroRepositoryImpl();
        tdMetroDao = mock(TdMetroDao.class);
        tdMetroRepositoryImpl.setTdMetroDao(tdMetroDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        TdMetro none = null;

        when(tdMetroDao.findUniqueOrNone(any(TdMetro.class), any(SearchParameters.class))).thenReturn(none);

        TdMetro result = tdMetroRepositoryImpl.findUniqueOrNone(new TdMetro());

        assertThat(result).isNull();
        verify(tdMetroDao, times(1)).findUniqueOrNone(any(TdMetro.class), any(SearchParameters.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        TdMetro unique = new TdMetro();

        when(tdMetroDao.findUniqueOrNone(any(TdMetro.class), any(SearchParameters.class))).thenReturn(unique);

        TdMetro result = tdMetroRepositoryImpl.findUniqueOrNone(new TdMetro());

        assertThat(result).isNotNull();
        verify(tdMetroDao, times(1)).findUniqueOrNone(any(TdMetro.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        when(tdMetroDao.findUniqueOrNone(any(TdMetro.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        tdMetroRepositoryImpl.findUniqueOrNone(new TdMetro());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void testFindUniqueCaseNone() {
        when(tdMetroDao.findUnique(any(TdMetro.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        tdMetroRepositoryImpl.findUnique(new TdMetro());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        TdMetro unique = new TdMetro();

        when(tdMetroDao.findUnique(any(TdMetro.class), any(SearchParameters.class))).thenReturn(unique);

        TdMetro result = tdMetroRepositoryImpl.findUnique(new TdMetro());

        assertThat(result).isNotNull();
        verify(tdMetroDao, times(1)).findUnique(any(TdMetro.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueCaseMultiple() {
        when(tdMetroDao.findUnique(any(TdMetro.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        tdMetroRepositoryImpl.findUnique(new TdMetro());
    }
}