/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.app.mpadmin.repository;

import java.util.Date;
import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import com.app.mpadmin.domain.TdOrder;
import com.app.mpadmin.domain.TdProduct;
import com.app.mpadmin.repository.TdProductGenerator;
import com.app.mpadmin.repository.TdProductRepository;
import com.app.mpadmin.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@SuppressWarnings("unused")
@Named
@Singleton
public class TdOrderGenerator {

    /**
     * Returns a new TdOrder instance filled with random values.
     */
    public TdOrder getTdOrder() {
        TdOrder tdOrder = new TdOrder();

        // simple attributes follows
        tdOrder.setBillingId(1);
        tdOrder.setInvoiceId(1);
        tdOrder.setUsername("a");
        tdOrder.setOrderFormNo("a");
        tdOrder.setOrderType(1);
        tdOrder.setOrderStatus(1);
        tdOrder.setOrderActive(1);
        tdOrder.setOrderChangeHistory("a");
        tdOrder.setOrderPriority(1);
        tdOrder.setOrderCorporateType(1);
        tdOrder.setOrderBulkType(1);
        tdOrder.setOrderDiscountCouponCode("a");
        tdOrder.setProductName("a");
        tdOrder.setProductQuantity(1);
        tdOrder.setAssignedToUseridDate(new Date());
        tdOrder.setBillingPhone1Blocked(1);
        tdOrder.setBillingPhone2Blocked(1);
        tdOrder.setBillingFirstname("a");
        tdOrder.setBillingLastname("a");
        tdOrder.setBillingEmail("dummy@dummy.com");
        tdOrder.setBillingPhone1("a");
        tdOrder.setBillingPhone2("a");
        tdOrder.setBillingAddressline1("a");
        tdOrder.setBillingAddressline2("a");
        tdOrder.setBillingZip("a");
        tdOrder.setBillingTotalAmount(1f);
        tdOrder.setBillingAdvanceAmount(1f);
        tdOrder.setBillingBalanceAmount(1f);
        tdOrder.setBillingMarginAmount(1f);
        tdOrder.setBillingTaxrate(1f);
        tdOrder.setBillingPaymentGatewayRate(1f);
        tdOrder.setShipmentRate(1f);
        tdOrder.setBillingGrossAmount(1f);
        tdOrder.setBillingNettCost(1f);
        tdOrder.setCustPaymentMode(1);
        tdOrder.setCustPaymentStatus(1);
        tdOrder.setCustPaymentDate(new Date());
        tdOrder.setCustPaymentComments("a");
        tdOrder.setCustPaymentId1("a");
        tdOrder.setCustPaymentId2("a");
        tdOrder.setVendorPaymentMode(1);
        tdOrder.setVendorPaymentDate(new Date());
        tdOrder.setVendorPaymentComments("a");
        tdOrder.setShipmentFirstname("a");
        tdOrder.setShipmentLastname("a");
        tdOrder.setShipmentEmail("dummy@dummy.com");
        tdOrder.setShipmentPhone1("a");
        tdOrder.setShipmentPhone2("a");
        tdOrder.setShipmentAddressline1("a");
        tdOrder.setShipmentAddressline2("a");
        tdOrder.setShipmentZip("a");
        tdOrder.setShipmentComments("a");
        tdOrder.setOrderOriginIpaddress("a");
        tdOrder.setOrderOriginCity("a");
        tdOrder.setOrderOriginCountryCode("dd");
        tdOrder.setOrderOriginCountryId(1);
        tdOrder.setOrderLeadsubmitUrl("http://www.jaxio.com");
        tdOrder.setOrderOriginRefUrl("http://www.jaxio.com");
        tdOrder.setOrderOriginalRefUrl("http://www.jaxio.com");
        tdOrder.setOrderBrowsingHistory("a");
        tdOrder.setOrderRefKeywords("a");
        tdOrder.setOrderRefSourceId1("a");
        tdOrder.setOrderRefSourceId2("a");
        tdOrder.setOrderRefCid("a");
        tdOrder.setOrderCreationDate(new Date());
        tdOrder.setOrderFirstUpdationDate(new Date());
        tdOrder.setOrderAvailabilityStatus(1);
        tdOrder.setOrderAvailabilityStatusUpdationDate(new Date());
        tdOrder.setDispatchAirwayId("a");
        tdOrder.setDispatchDate(new Date());
        tdOrder.setDeliveryDate(new Date());
        tdOrder.setDeliveryStatus(1);
        tdOrder.setMailedReminderToVendorStatus(1);
        tdOrder.setMailedReminderToVendorDate(new Date());
        tdOrder.setOrderCancelRequestStatus(1);
        tdOrder.setOrderCancelRequestDate(new Date());
        tdOrder.setOrderCancellationToVendorStatus(1);
        tdOrder.setOrderCancellationToVendorDate(new Date());
        tdOrder.setOrderConversionDate(new Date());
        tdOrder.setOrderConfirmationDate(new Date());
        tdOrder.setOrderConfirmationComments("a");
        tdOrder.setOrderReconfirmationDate(new Date());
        tdOrder.setOrderReconfirmationComments("a");
        tdOrder.setOrderCancellationType(1);
        tdOrder.setOrderCancellationComments("a");
        tdOrder.setOrderCancellationDate(new Date());
        tdOrder.setOrderRefundType(1);
        tdOrder.setOrderRefundComments("a");
        tdOrder.setOrderRefundDate(new Date());
        tdOrder.setDisputeRaisedStatus(1);
        tdOrder.setDisputeRaisedDate(new Date());
        tdOrder.setDisputeRaisedComments("a");
        tdOrder.setOrderLastUpdationDate(new Date());
        tdOrder.setOrderAcceptNewsletter(1);
        tdOrder.setOrderAcceptPromotionalMaterial(1);
        tdOrder.setOrderInternalNarration("a");
        tdOrder.setCustom1("a");
        tdOrder.setCustom2("a");
        tdOrder.setCustomint1(1);
        tdOrder.setCustomint2(1);
        tdOrder.setIpaddress("a");
        tdOrder.setCarMake("a");
        tdOrder.setCarModel("a");
        tdOrder.setCarYear(1);
        tdOrder.setFuelType("a");
        tdOrder.setOrderOriginRegion("a");
        // mandatory relation
        TdProduct product = tdProductGenerator.getTdProduct();
        tdProductRepository.save(product);
        tdOrder.setProduct(product);
        return tdOrder;
    }

    @Inject
    private TdProductRepository tdProductRepository;
    @Inject
    private TdProductGenerator tdProductGenerator;
}