/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ServiceImplTest.e.vm.java
 */
package com.app.mpadmin.repository;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Before;
import org.junit.Test;

import com.app.mpadmin.domain.TdPage;
import com.app.mpadmin.repository.TdPageRepositoryImpl;
import com.app.mpadmin.dao.TdPageDao;
import com.app.mpadmin.dao.support.SearchParameters;

/**
 * Unit test on TdPageRepositoryImpl
 */
public class TdPageRepositoryImplTest {

    private TdPageRepositoryImpl tdPageRepositoryImpl;
    private TdPageDao tdPageDao;

    @Before
    public void setUp() {
        // called before each test.
        tdPageRepositoryImpl = new TdPageRepositoryImpl();
        tdPageDao = mock(TdPageDao.class);
        tdPageRepositoryImpl.setTdPageDao(tdPageDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        TdPage none = null;

        when(tdPageDao.findUniqueOrNone(any(TdPage.class), any(SearchParameters.class))).thenReturn(none);

        TdPage result = tdPageRepositoryImpl.findUniqueOrNone(new TdPage());

        assertThat(result).isNull();
        verify(tdPageDao, times(1)).findUniqueOrNone(any(TdPage.class), any(SearchParameters.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        TdPage unique = new TdPage();

        when(tdPageDao.findUniqueOrNone(any(TdPage.class), any(SearchParameters.class))).thenReturn(unique);

        TdPage result = tdPageRepositoryImpl.findUniqueOrNone(new TdPage());

        assertThat(result).isNotNull();
        verify(tdPageDao, times(1)).findUniqueOrNone(any(TdPage.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        when(tdPageDao.findUniqueOrNone(any(TdPage.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        tdPageRepositoryImpl.findUniqueOrNone(new TdPage());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void testFindUniqueCaseNone() {
        when(tdPageDao.findUnique(any(TdPage.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        tdPageRepositoryImpl.findUnique(new TdPage());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        TdPage unique = new TdPage();

        when(tdPageDao.findUnique(any(TdPage.class), any(SearchParameters.class))).thenReturn(unique);

        TdPage result = tdPageRepositoryImpl.findUnique(new TdPage());

        assertThat(result).isNotNull();
        verify(tdPageDao, times(1)).findUnique(any(TdPage.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueCaseMultiple() {
        when(tdPageDao.findUnique(any(TdPage.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        tdPageRepositoryImpl.findUnique(new TdPage());
    }
}