/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ServiceImplTest.e.vm.java
 */
package com.app.mpadmin.repository;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Before;
import org.junit.Test;

import com.app.mpadmin.domain.TdProductSubmodel;
import com.app.mpadmin.repository.TdProductSubmodelRepositoryImpl;
import com.app.mpadmin.dao.TdProductSubmodelDao;
import com.app.mpadmin.dao.support.SearchParameters;

/**
 * Unit test on TdProductSubmodelRepositoryImpl
 */
public class TdProductSubmodelRepositoryImplTest {

    private TdProductSubmodelRepositoryImpl tdProductSubmodelRepositoryImpl;
    private TdProductSubmodelDao tdProductSubmodelDao;

    @Before
    public void setUp() {
        // called before each test.
        tdProductSubmodelRepositoryImpl = new TdProductSubmodelRepositoryImpl();
        tdProductSubmodelDao = mock(TdProductSubmodelDao.class);
        tdProductSubmodelRepositoryImpl.setTdProductSubmodelDao(tdProductSubmodelDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        TdProductSubmodel none = null;

        when(tdProductSubmodelDao.findUniqueOrNone(any(TdProductSubmodel.class), any(SearchParameters.class))).thenReturn(none);

        TdProductSubmodel result = tdProductSubmodelRepositoryImpl.findUniqueOrNone(new TdProductSubmodel());

        assertThat(result).isNull();
        verify(tdProductSubmodelDao, times(1)).findUniqueOrNone(any(TdProductSubmodel.class), any(SearchParameters.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        TdProductSubmodel unique = new TdProductSubmodel();

        when(tdProductSubmodelDao.findUniqueOrNone(any(TdProductSubmodel.class), any(SearchParameters.class))).thenReturn(unique);

        TdProductSubmodel result = tdProductSubmodelRepositoryImpl.findUniqueOrNone(new TdProductSubmodel());

        assertThat(result).isNotNull();
        verify(tdProductSubmodelDao, times(1)).findUniqueOrNone(any(TdProductSubmodel.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        when(tdProductSubmodelDao.findUniqueOrNone(any(TdProductSubmodel.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        tdProductSubmodelRepositoryImpl.findUniqueOrNone(new TdProductSubmodel());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void testFindUniqueCaseNone() {
        when(tdProductSubmodelDao.findUnique(any(TdProductSubmodel.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        tdProductSubmodelRepositoryImpl.findUnique(new TdProductSubmodel());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        TdProductSubmodel unique = new TdProductSubmodel();

        when(tdProductSubmodelDao.findUnique(any(TdProductSubmodel.class), any(SearchParameters.class))).thenReturn(unique);

        TdProductSubmodel result = tdProductSubmodelRepositoryImpl.findUnique(new TdProductSubmodel());

        assertThat(result).isNotNull();
        verify(tdProductSubmodelDao, times(1)).findUnique(any(TdProductSubmodel.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueCaseMultiple() {
        when(tdProductSubmodelDao.findUnique(any(TdProductSubmodel.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        tdProductSubmodelRepositoryImpl.findUnique(new TdProductSubmodel());
    }
}