/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ServiceImplTest.e.vm.java
 */
package com.app.mpadmin.repository;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Before;
import org.junit.Test;

import com.app.mpadmin.domain.TdProductShipment;
import com.app.mpadmin.repository.TdProductShipmentRepositoryImpl;
import com.app.mpadmin.dao.TdProductShipmentDao;
import com.app.mpadmin.dao.support.SearchParameters;

/**
 * Unit test on TdProductShipmentRepositoryImpl
 */
public class TdProductShipmentRepositoryImplTest {

    private TdProductShipmentRepositoryImpl tdProductShipmentRepositoryImpl;
    private TdProductShipmentDao tdProductShipmentDao;

    @Before
    public void setUp() {
        // called before each test.
        tdProductShipmentRepositoryImpl = new TdProductShipmentRepositoryImpl();
        tdProductShipmentDao = mock(TdProductShipmentDao.class);
        tdProductShipmentRepositoryImpl.setTdProductShipmentDao(tdProductShipmentDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        TdProductShipment none = null;

        when(tdProductShipmentDao.findUniqueOrNone(any(TdProductShipment.class), any(SearchParameters.class))).thenReturn(none);

        TdProductShipment result = tdProductShipmentRepositoryImpl.findUniqueOrNone(new TdProductShipment());

        assertThat(result).isNull();
        verify(tdProductShipmentDao, times(1)).findUniqueOrNone(any(TdProductShipment.class), any(SearchParameters.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        TdProductShipment unique = new TdProductShipment();

        when(tdProductShipmentDao.findUniqueOrNone(any(TdProductShipment.class), any(SearchParameters.class))).thenReturn(unique);

        TdProductShipment result = tdProductShipmentRepositoryImpl.findUniqueOrNone(new TdProductShipment());

        assertThat(result).isNotNull();
        verify(tdProductShipmentDao, times(1)).findUniqueOrNone(any(TdProductShipment.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        when(tdProductShipmentDao.findUniqueOrNone(any(TdProductShipment.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        tdProductShipmentRepositoryImpl.findUniqueOrNone(new TdProductShipment());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void testFindUniqueCaseNone() {
        when(tdProductShipmentDao.findUnique(any(TdProductShipment.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        tdProductShipmentRepositoryImpl.findUnique(new TdProductShipment());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        TdProductShipment unique = new TdProductShipment();

        when(tdProductShipmentDao.findUnique(any(TdProductShipment.class), any(SearchParameters.class))).thenReturn(unique);

        TdProductShipment result = tdProductShipmentRepositoryImpl.findUnique(new TdProductShipment());

        assertThat(result).isNotNull();
        verify(tdProductShipmentDao, times(1)).findUnique(any(TdProductShipment.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueCaseMultiple() {
        when(tdProductShipmentDao.findUnique(any(TdProductShipment.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        tdProductShipmentRepositoryImpl.findUnique(new TdProductShipment());
    }
}