/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ServiceImplTest.e.vm.java
 */
package com.app.mpadmin.repository;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Before;
import org.junit.Test;

import com.app.mpadmin.domain.TdProduct;
import com.app.mpadmin.repository.TdProductRepositoryImpl;
import com.app.mpadmin.dao.TdProductDao;
import com.app.mpadmin.dao.support.SearchParameters;

/**
 * Unit test on TdProductRepositoryImpl
 */
public class TdProductRepositoryImplTest {

    private TdProductRepositoryImpl tdProductRepositoryImpl;
    private TdProductDao tdProductDao;

    @Before
    public void setUp() {
        // called before each test.
        tdProductRepositoryImpl = new TdProductRepositoryImpl();
        tdProductDao = mock(TdProductDao.class);
        tdProductRepositoryImpl.setTdProductDao(tdProductDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        TdProduct none = null;

        when(tdProductDao.findUniqueOrNone(any(TdProduct.class), any(SearchParameters.class))).thenReturn(none);

        TdProduct result = tdProductRepositoryImpl.findUniqueOrNone(new TdProduct());

        assertThat(result).isNull();
        verify(tdProductDao, times(1)).findUniqueOrNone(any(TdProduct.class), any(SearchParameters.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        TdProduct unique = new TdProduct();

        when(tdProductDao.findUniqueOrNone(any(TdProduct.class), any(SearchParameters.class))).thenReturn(unique);

        TdProduct result = tdProductRepositoryImpl.findUniqueOrNone(new TdProduct());

        assertThat(result).isNotNull();
        verify(tdProductDao, times(1)).findUniqueOrNone(any(TdProduct.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        when(tdProductDao.findUniqueOrNone(any(TdProduct.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        tdProductRepositoryImpl.findUniqueOrNone(new TdProduct());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void testFindUniqueCaseNone() {
        when(tdProductDao.findUnique(any(TdProduct.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        tdProductRepositoryImpl.findUnique(new TdProduct());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        TdProduct unique = new TdProduct();

        when(tdProductDao.findUnique(any(TdProduct.class), any(SearchParameters.class))).thenReturn(unique);

        TdProduct result = tdProductRepositoryImpl.findUnique(new TdProduct());

        assertThat(result).isNotNull();
        verify(tdProductDao, times(1)).findUnique(any(TdProduct.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueCaseMultiple() {
        when(tdProductDao.findUnique(any(TdProduct.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        tdProductRepositoryImpl.findUnique(new TdProduct());
    }
}