/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ServiceImplTest.e.vm.java
 */
package com.app.mpadmin.repository;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Before;
import org.junit.Test;

import com.app.mpadmin.domain.TdRequestCarPart;
import com.app.mpadmin.repository.TdRequestCarPartRepositoryImpl;
import com.app.mpadmin.dao.TdRequestCarPartDao;
import com.app.mpadmin.dao.support.SearchParameters;

/**
 * Unit test on TdRequestCarPartRepositoryImpl
 */
public class TdRequestCarPartRepositoryImplTest {

    private TdRequestCarPartRepositoryImpl tdRequestCarPartRepositoryImpl;
    private TdRequestCarPartDao tdRequestCarPartDao;

    @Before
    public void setUp() {
        // called before each test.
        tdRequestCarPartRepositoryImpl = new TdRequestCarPartRepositoryImpl();
        tdRequestCarPartDao = mock(TdRequestCarPartDao.class);
        tdRequestCarPartRepositoryImpl.setTdRequestCarPartDao(tdRequestCarPartDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        TdRequestCarPart none = null;

        when(tdRequestCarPartDao.findUniqueOrNone(any(TdRequestCarPart.class), any(SearchParameters.class))).thenReturn(none);

        TdRequestCarPart result = tdRequestCarPartRepositoryImpl.findUniqueOrNone(new TdRequestCarPart());

        assertThat(result).isNull();
        verify(tdRequestCarPartDao, times(1)).findUniqueOrNone(any(TdRequestCarPart.class), any(SearchParameters.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        TdRequestCarPart unique = new TdRequestCarPart();

        when(tdRequestCarPartDao.findUniqueOrNone(any(TdRequestCarPart.class), any(SearchParameters.class))).thenReturn(unique);

        TdRequestCarPart result = tdRequestCarPartRepositoryImpl.findUniqueOrNone(new TdRequestCarPart());

        assertThat(result).isNotNull();
        verify(tdRequestCarPartDao, times(1)).findUniqueOrNone(any(TdRequestCarPart.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        when(tdRequestCarPartDao.findUniqueOrNone(any(TdRequestCarPart.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        tdRequestCarPartRepositoryImpl.findUniqueOrNone(new TdRequestCarPart());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void testFindUniqueCaseNone() {
        when(tdRequestCarPartDao.findUnique(any(TdRequestCarPart.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        tdRequestCarPartRepositoryImpl.findUnique(new TdRequestCarPart());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        TdRequestCarPart unique = new TdRequestCarPart();

        when(tdRequestCarPartDao.findUnique(any(TdRequestCarPart.class), any(SearchParameters.class))).thenReturn(unique);

        TdRequestCarPart result = tdRequestCarPartRepositoryImpl.findUnique(new TdRequestCarPart());

        assertThat(result).isNotNull();
        verify(tdRequestCarPartDao, times(1)).findUnique(any(TdRequestCarPart.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueCaseMultiple() {
        when(tdRequestCarPartDao.findUnique(any(TdRequestCarPart.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        tdRequestCarPartRepositoryImpl.findUnique(new TdRequestCarPart());
    }
}