/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ServiceImplTest.e.vm.java
 */
package com.app.mpadmin.repository;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Before;
import org.junit.Test;

import com.app.mpadmin.domain.TdRole;
import com.app.mpadmin.repository.TdRoleRepositoryImpl;
import com.app.mpadmin.dao.TdRoleDao;
import com.app.mpadmin.dao.support.SearchParameters;

/**
 * Unit test on TdRoleRepositoryImpl
 */
public class TdRoleRepositoryImplTest {

    private TdRoleRepositoryImpl tdRoleRepositoryImpl;
    private TdRoleDao tdRoleDao;

    @Before
    public void setUp() {
        // called before each test.
        tdRoleRepositoryImpl = new TdRoleRepositoryImpl();
        tdRoleDao = mock(TdRoleDao.class);
        tdRoleRepositoryImpl.setTdRoleDao(tdRoleDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        TdRole none = null;

        when(tdRoleDao.findUniqueOrNone(any(TdRole.class), any(SearchParameters.class))).thenReturn(none);

        TdRole result = tdRoleRepositoryImpl.findUniqueOrNone(new TdRole());

        assertThat(result).isNull();
        verify(tdRoleDao, times(1)).findUniqueOrNone(any(TdRole.class), any(SearchParameters.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        TdRole unique = new TdRole();

        when(tdRoleDao.findUniqueOrNone(any(TdRole.class), any(SearchParameters.class))).thenReturn(unique);

        TdRole result = tdRoleRepositoryImpl.findUniqueOrNone(new TdRole());

        assertThat(result).isNotNull();
        verify(tdRoleDao, times(1)).findUniqueOrNone(any(TdRole.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        when(tdRoleDao.findUniqueOrNone(any(TdRole.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        tdRoleRepositoryImpl.findUniqueOrNone(new TdRole());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void testFindUniqueCaseNone() {
        when(tdRoleDao.findUnique(any(TdRole.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        tdRoleRepositoryImpl.findUnique(new TdRole());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        TdRole unique = new TdRole();

        when(tdRoleDao.findUnique(any(TdRole.class), any(SearchParameters.class))).thenReturn(unique);

        TdRole result = tdRoleRepositoryImpl.findUnique(new TdRole());

        assertThat(result).isNotNull();
        verify(tdRoleDao, times(1)).findUnique(any(TdRole.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueCaseMultiple() {
        when(tdRoleDao.findUnique(any(TdRole.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        tdRoleRepositoryImpl.findUnique(new TdRole());
    }
}