/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.app.mpadmin.repository;

import java.util.Date;
import javax.inject.Named;
import javax.inject.Singleton;
import com.app.mpadmin.domain.TdRole;
import com.app.mpadmin.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@SuppressWarnings("unused")
@Named
@Singleton
public class TdRoleGenerator {

    /**
     * Returns a new TdRole instance filled with random values.
     */
    public TdRole getTdRole() {
        TdRole tdRole = new TdRole();

        // simple attributes follows
        tdRole.setRoleName("a");
        tdRole.setCreationDate(new Date());
        tdRole.setUpdationDate(new Date());
        tdRole.setIsActive(1);
        return tdRole;
    }

}