/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.app.mpadmin.repository;

import java.util.Date;
import javax.inject.Named;
import javax.inject.Singleton;
import com.app.mpadmin.domain.TdUserDetail;
import com.app.mpadmin.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@SuppressWarnings("unused")
@Named
@Singleton
public class TdUserDetailGenerator {

    /**
     * Returns a new TdUserDetail instance filled with random values.
     */
    public TdUserDetail getTdUserDetail() {
        TdUserDetail tdUserDetail = new TdUserDetail();

        // simple attributes follows
        tdUserDetail.setFirstname("a");
        tdUserDetail.setLastname("a");
        tdUserDetail.setIsActive(1);
        tdUserDetail.setDob(new Date());
        tdUserDetail.setPhone(1);
        tdUserDetail.setInterest("a");
        tdUserDetail.setCreationDate(new Date());
        tdUserDetail.setUpdationDate(new Date());
        tdUserDetail.setCredit(1);
        return tdUserDetail;
    }

}