/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.app.mpadmin.repository;

import java.util.Date;
import javax.inject.Named;
import javax.inject.Singleton;
import com.app.mpadmin.domain.TdUserTagPreference;
import com.app.mpadmin.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@SuppressWarnings("unused")
@Named
@Singleton
public class TdUserTagPreferenceGenerator {

    /**
     * Returns a new TdUserTagPreference instance filled with random values.
     */
    public TdUserTagPreference getTdUserTagPreference() {
        TdUserTagPreference tdUserTagPreference = new TdUserTagPreference();

        // primary key column must be set manually
        tdUserTagPreference.setUserTagPreferenceId(ValueGenerator.getUniqueInteger());
        // simple attributes follows
        tdUserTagPreference.setCreationDate(new Date());
        tdUserTagPreference.setUpdationDate(new Date());
        return tdUserTagPreference;
    }

}