/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity_.e.vm.java
 */
package com.app.mpadmin.domain;

import java.util.Date;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(AuthUser.class)
public abstract class AuthUser_ {

    // Raw attributes
    public static volatile SingularAttribute<AuthUser, Integer> id;
    public static volatile SingularAttribute<AuthUser, String> username;
    public static volatile SingularAttribute<AuthUser, String> firstName;
    public static volatile SingularAttribute<AuthUser, String> lastName;
    public static volatile SingularAttribute<AuthUser, String> email;
    public static volatile SingularAttribute<AuthUser, String> password;
    public static volatile SingularAttribute<AuthUser, Boolean> isStaff;
    public static volatile SingularAttribute<AuthUser, Boolean> isActive;
    public static volatile SingularAttribute<AuthUser, Boolean> isSuperuser;
    public static volatile SingularAttribute<AuthUser, Date> lastLogin;
    public static volatile SingularAttribute<AuthUser, Date> dateJoined;
}