/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity_.e.vm.java
 */
package com.app.mpadmin.domain;

import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(TdMakeSubmodel.class)
public abstract class TdMakeSubmodel_ {

    // Raw attributes
    public static volatile SingularAttribute<TdMakeSubmodel, Double> makeSubmodelId;
    public static volatile SingularAttribute<TdMakeSubmodel, Double> makeModelId;
    public static volatile SingularAttribute<TdMakeSubmodel, String> makesubmodelDisplayName;
    public static volatile SingularAttribute<TdMakeSubmodel, String> makesubmodelTechnicalName;
    public static volatile SingularAttribute<TdMakeSubmodel, String> makesubmodelAlternateName;
    public static volatile SingularAttribute<TdMakeSubmodel, String> shortDesc;
    public static volatile SingularAttribute<TdMakeSubmodel, byte[]> longDesc;
    public static volatile SingularAttribute<TdMakeSubmodel, Integer> submodelLaunchYear;
    public static volatile SingularAttribute<TdMakeSubmodel, Integer> fuelType;
    public static volatile SingularAttribute<TdMakeSubmodel, Integer> transmissionType;
    public static volatile SingularAttribute<TdMakeSubmodel, Integer> wheeldriveType;
    public static volatile SingularAttribute<TdMakeSubmodel, Integer> engineCapacity;
    public static volatile SingularAttribute<TdMakeSubmodel, Integer> bodyType;
    public static volatile SingularAttribute<TdMakeSubmodel, Integer> doorCount;
    public static volatile SingularAttribute<TdMakeSubmodel, Integer> gearCount;
    public static volatile SingularAttribute<TdMakeSubmodel, Integer> fuelDelivery;
    public static volatile SingularAttribute<TdMakeSubmodel, Integer> valvesCount;
    public static volatile SingularAttribute<TdMakeSubmodel, Integer> isActive;
    public static volatile SingularAttribute<TdMakeSubmodel, Integer> bhp;
    public static volatile SingularAttribute<TdMakeSubmodel, Integer> torque;
    public static volatile SingularAttribute<TdMakeSubmodel, Integer> submodelType;
    public static volatile SingularAttribute<TdMakeSubmodel, String> specialEditionName;
    public static volatile SingularAttribute<TdMakeSubmodel, String> specialEditionInfo;
    public static volatile SingularAttribute<TdMakeSubmodel, Integer> specialEditionYear;
    public static volatile SingularAttribute<TdMakeSubmodel, Integer> makesubmodelStatus;
    public static volatile SingularAttribute<TdMakeSubmodel, String> seoResources;
    public static volatile SingularAttribute<TdMakeSubmodel, String> seoUrl;
    public static volatile SingularAttribute<TdMakeSubmodel, String> seoH1;
    public static volatile SingularAttribute<TdMakeSubmodel, String> seoH2;
    public static volatile SingularAttribute<TdMakeSubmodel, String> metaTitle;
    public static volatile SingularAttribute<TdMakeSubmodel, String> metaKeyword;
    public static volatile SingularAttribute<TdMakeSubmodel, String> metaDescription;
    public static volatile SingularAttribute<TdMakeSubmodel, String> custom1;
    public static volatile SingularAttribute<TdMakeSubmodel, String> custom2;
    public static volatile SingularAttribute<TdMakeSubmodel, String> custom3;
    public static volatile SingularAttribute<TdMakeSubmodel, Date> creationDate;
    public static volatile SingularAttribute<TdMakeSubmodel, Date> updationDate;
}