/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity_.e.vm.java
 */
package com.app.mpadmin.domain;

import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(TdMetro.class)
public abstract class TdMetro_ {

    // Raw attributes
    public static volatile SingularAttribute<TdMetro, Integer> metroId;
    public static volatile SingularAttribute<TdMetro, String> metroName;
    public static volatile SingularAttribute<TdMetro, String> metroName2;
    public static volatile SingularAttribute<TdMetro, String> metroName3;
    public static volatile SingularAttribute<TdMetro, Integer> importance;
    public static volatile SingularAttribute<TdMetro, Integer> flag;
    public static volatile SingularAttribute<TdMetro, Date> creationDate;
    public static volatile SingularAttribute<TdMetro, Date> updationDate;
}