/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity.e.vm.java
 */
package com.app.mpadmin.domain;

import static javax.persistence.TemporalType.TIMESTAMP;
import static org.hibernate.annotations.CacheConcurrencyStrategy.NONSTRICT_READ_WRITE;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;
import org.apache.log4j.Logger;
import org.hibernate.annotations.Cache;
import org.hibernate.validator.constraints.NotEmpty;
import org.hibernate.validator.constraints.URL;
import com.google.common.base.Objects;

@Entity
@Table(name = "td_product_brand")
@Cache(usage = NONSTRICT_READ_WRITE)
public class TdProductBrand implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(TdProductBrand.class);

    // Raw attributes
    private Integer productBrandId; // pk
    private String brandDisplayName; // not null
    private String brandAlternateName;
    private String shortDesc;
    private String longDesc;
    private Integer internalRating;
    private String refLink1;
    private String refLink2;
    private Boolean brandStatus; // not null
    private String custom1;
    private String custom2;
    private String custom3;
    private String seoResources;
    private String seoUrl; // unique (but null allowed)
    private String seoH1;
    private String seoH2;
    private String metaTitle;
    private String metaKeyword;
    private String metaDescription;
    private Date creationDate;
    private Date updationDate;
    private Integer isActive;

    // ---------------------------
    // Constructors
    // ---------------------------

    public TdProductBrand() {
    }

    public TdProductBrand(Integer primaryKey) {
        setId(primaryKey);
    }

    // ---------------------------
    // Identifiable implementation
    // ---------------------------

    @Override
    @Transient
    @XmlTransient
    public Integer getId() {
        return getProductBrandId();
    }

    @Override
    public void setId(Integer productBrandId) {
        setProductBrandId(productBrandId);
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return isProductBrandIdSet();
    }

    // -------------------------------
    // Getter & Setter
    // -------------------------------

    // -- [productBrandId] ------------------------

    @Column(name = "product_brand_id", precision = 10)
    @GeneratedValue
    @Id
    public Integer getProductBrandId() {
        return productBrandId;
    }

    public void setProductBrandId(Integer productBrandId) {
        this.productBrandId = productBrandId;
    }

    @Transient
    public boolean isProductBrandIdSet() {
        return productBrandId != null;
    }

    // -- [brandDisplayName] ------------------------

    @Size(max = 256)
    @NotEmpty
    @Column(name = "brand_display_name", nullable = false, length = 256)
    public String getBrandDisplayName() {
        return brandDisplayName;
    }

    public void setBrandDisplayName(String brandDisplayName) {
        this.brandDisplayName = brandDisplayName;
    }

    // -- [brandAlternateName] ------------------------

    @Size(max = 256)
    @Column(name = "brand_alternate_name", length = 256)
    public String getBrandAlternateName() {
        return brandAlternateName;
    }

    public void setBrandAlternateName(String brandAlternateName) {
        this.brandAlternateName = brandAlternateName;
    }

    // -- [shortDesc] ------------------------

    @Size(max = 1024)
    @Column(name = "short_desc", length = 1024)
    public String getShortDesc() {
        return shortDesc;
    }

    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
    }

    // -- [longDesc] ------------------------

    @Size(max = 4096)
    @Column(name = "long_desc", length = 4096)
    public String getLongDesc() {
        return longDesc;
    }

    public void setLongDesc(String longDesc) {
        this.longDesc = longDesc;
    }

    // -- [internalRating] ------------------------

    @Column(name = "internal_rating", precision = 5)
    public Integer getInternalRating() {
        return internalRating;
    }

    public void setInternalRating(Integer internalRating) {
        this.internalRating = internalRating;
    }

    // -- [refLink1] ------------------------

    @Size(max = 512)
    @Column(name = "ref_link1", length = 512)
    public String getRefLink1() {
        return refLink1;
    }

    public void setRefLink1(String refLink1) {
        this.refLink1 = refLink1;
    }

    // -- [refLink2] ------------------------

    @Size(max = 512)
    @Column(name = "ref_link2", length = 512)
    public String getRefLink2() {
        return refLink2;
    }

    public void setRefLink2(String refLink2) {
        this.refLink2 = refLink2;
    }

    // -- [brandStatus] ------------------------

    @NotNull
    @Column(name = "brand_status", nullable = false, length = 0)
    public Boolean getBrandStatus() {
        return brandStatus;
    }

    public void setBrandStatus(Boolean brandStatus) {
        this.brandStatus = brandStatus;
    }

    // -- [custom1] ------------------------

    @Size(max = 1024)
    @Column(length = 1024)
    public String getCustom1() {
        return custom1;
    }

    public void setCustom1(String custom1) {
        this.custom1 = custom1;
    }

    // -- [custom2] ------------------------

    @Size(max = 1024)
    @Column(length = 1024)
    public String getCustom2() {
        return custom2;
    }

    public void setCustom2(String custom2) {
        this.custom2 = custom2;
    }

    // -- [custom3] ------------------------

    @Size(max = 1024)
    @Column(length = 1024)
    public String getCustom3() {
        return custom3;
    }

    public void setCustom3(String custom3) {
        this.custom3 = custom3;
    }

    // -- [seoResources] ------------------------

    @Size(max = 256)
    @Column(name = "seo_resources", length = 256)
    public String getSeoResources() {
        return seoResources;
    }

    public void setSeoResources(String seoResources) {
        this.seoResources = seoResources;
    }

    // -- [seoUrl] ------------------------

    @Size(max = 512)
    @URL
    @Column(name = "seo_url", unique = true, length = 512)
    public String getSeoUrl() {
        return seoUrl;
    }

    public void setSeoUrl(String seoUrl) {
        this.seoUrl = seoUrl;
    }

    // -- [seoH1] ------------------------

    @Size(max = 256)
    @Column(name = "seo_h1", length = 256)
    public String getSeoH1() {
        return seoH1;
    }

    public void setSeoH1(String seoH1) {
        this.seoH1 = seoH1;
    }

    // -- [seoH2] ------------------------

    @Size(max = 256)
    @Column(name = "seo_h2", length = 256)
    public String getSeoH2() {
        return seoH2;
    }

    public void setSeoH2(String seoH2) {
        this.seoH2 = seoH2;
    }

    // -- [metaTitle] ------------------------

    @Size(max = 512)
    @Column(name = "meta_title", length = 512)
    public String getMetaTitle() {
        return metaTitle;
    }

    public void setMetaTitle(String metaTitle) {
        this.metaTitle = metaTitle;
    }

    // -- [metaKeyword] ------------------------

    @Size(max = 512)
    @Column(name = "meta_keyword", length = 512)
    public String getMetaKeyword() {
        return metaKeyword;
    }

    public void setMetaKeyword(String metaKeyword) {
        this.metaKeyword = metaKeyword;
    }

    // -- [metaDescription] ------------------------

    @Size(max = 512)
    @Column(name = "meta_description", length = 512)
    public String getMetaDescription() {
        return metaDescription;
    }

    public void setMetaDescription(String metaDescription) {
        this.metaDescription = metaDescription;
    }

    // -- [creationDate] ------------------------

    @Column(name = "creation_date", length = 19)
    @Temporal(TIMESTAMP)
    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    // -- [updationDate] ------------------------

    @Column(name = "updation_date", length = 19)
    @Temporal(TIMESTAMP)
    public Date getUpdationDate() {
        return updationDate;
    }

    public void setUpdationDate(Date updationDate) {
        this.updationDate = updationDate;
    }

    // -- [isActive] ------------------------

    @Column(name = "is_active", precision = 5)
    public Integer getIsActive() {
        return isActive;
    }

    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

    /**
     * Set the default values.
     */
    public void initDefaultValues() {
        setBrandStatus(false);
    }

    /**
     * equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof TdProductBrand && hashCode() == other.hashCode());
    }

    private volatile int previousHashCode = 0;

    @Override
    public int hashCode() {
        int hashCode = Objects.hashCode(getSeoUrl());
        if (previousHashCode != 0 && previousHashCode != hashCode) {
            log.warn("DEVELOPER: hashCode has changed!." //
                    + "If you encounter this message you should take the time to carefuly review equals/hashCode for: " //
                    + getClass().getCanonicalName());
        }

        previousHashCode = hashCode;
        return hashCode;
    }

    /**
     * Construct a readable string representation for this TdProductBrand instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add("productBrandId", getProductBrandId()) //
                .add("brandDisplayName", getBrandDisplayName()) //
                .add("brandAlternateName", getBrandAlternateName()) //
                .add("shortDesc", getShortDesc()) //
                .add("longDesc", getLongDesc()) //
                .add("internalRating", getInternalRating()) //
                .add("refLink1", getRefLink1()) //
                .add("refLink2", getRefLink2()) //
                .add("brandStatus", getBrandStatus()) //
                .add("custom1", getCustom1()) //
                .add("custom2", getCustom2()) //
                .add("custom3", getCustom3()) //
                .add("seoResources", getSeoResources()) //
                .add("seoUrl", getSeoUrl()) //
                .add("seoH1", getSeoH1()) //
                .add("seoH2", getSeoH2()) //
                .add("metaTitle", getMetaTitle()) //
                .add("metaKeyword", getMetaKeyword()) //
                .add("metaDescription", getMetaDescription()) //
                .add("creationDate", getCreationDate()) //
                .add("updationDate", getUpdationDate()) //
                .add("isActive", getIsActive()) //
                .toString();
    }

    @PrePersist
    protected void prePersist() {
        setCreationDate(new Date());
    }
}