/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity_.e.vm.java
 */
package com.app.mpadmin.domain;

import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import com.app.mpadmin.domain.TdShipmentVendor;

@StaticMetamodel(TdProductShipment.class)
public abstract class TdProductShipment_ {

    // Raw attributes
    public static volatile SingularAttribute<TdProductShipment, Integer> productShipmentId;
    public static volatile SingularAttribute<TdProductShipment, Float> shipmentMrpCost;
    public static volatile SingularAttribute<TdProductShipment, Float> shipmentDiscount;
    public static volatile SingularAttribute<TdProductShipment, String> shipmentPolicy;
    public static volatile SingularAttribute<TdProductShipment, String> shipmentSpecialNote;
    public static volatile SingularAttribute<TdProductShipment, Integer> shipmentDuration;
    public static volatile SingularAttribute<TdProductShipment, Integer> shipmentType;
    public static volatile SingularAttribute<TdProductShipment, Boolean> shipmentStatus;
    public static volatile SingularAttribute<TdProductShipment, String> custom1;
    public static volatile SingularAttribute<TdProductShipment, String> custom2;
    public static volatile SingularAttribute<TdProductShipment, Date> creationDate;
    public static volatile SingularAttribute<TdProductShipment, Date> updationDate;

    // Technical attributes for query by example
    public static volatile SingularAttribute<TdProductShipment, Integer> shipmentVendorId;

    // Many to one
    public static volatile SingularAttribute<TdProductShipment, TdShipmentVendor> shipmentVendor;
}