/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity_.e.vm.java
 */
package com.app.mpadmin.domain;

import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import com.app.mpadmin.domain.TdCountry;

@StaticMetamodel(TdState.class)
public abstract class TdState_ {

    // Raw attributes
    public static volatile SingularAttribute<TdState, Integer> stateId;
    public static volatile SingularAttribute<TdState, String> stateName;
    public static volatile SingularAttribute<TdState, Integer> importance;
    public static volatile SingularAttribute<TdState, String> descShort;
    public static volatile SingularAttribute<TdState, String> descLong;
    public static volatile SingularAttribute<TdState, Date> creationDate;
    public static volatile SingularAttribute<TdState, Date> updationDate;

    // Technical attributes for query by example
    public static volatile SingularAttribute<TdState, Integer> countryId;

    // Many to one
    public static volatile SingularAttribute<TdState, TdCountry> country;
}