/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity.e.vm.java
 */
package com.app.mpadmin.domain;

import static javax.persistence.TemporalType.TIMESTAMP;
import static org.hibernate.annotations.CacheConcurrencyStrategy.NONSTRICT_READ_WRITE;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;
import org.apache.log4j.Logger;
import org.hibernate.annotations.Cache;
import org.hibernate.validator.constraints.URL;
import com.app.mpadmin.domain.PersistableHashBuilder;
import com.google.common.base.Objects;

@Entity
@Table(name = "td_tag")
@Cache(usage = NONSTRICT_READ_WRITE)
public class TdTag implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(TdTag.class);

    // Raw attributes
    private Integer tagId; // pk
    private String tagTitle;
    private Integer tagPriority;
    private Integer tagType;
    private String tagDesc;
    private String tagUrl;
    private Date creationDate;
    private Date updationDate;
    private Integer isActive;
    private Integer tagStatus;

    // ---------------------------
    // Constructors
    // ---------------------------

    public TdTag() {
    }

    public TdTag(Integer primaryKey) {
        setId(primaryKey);
    }

    // ---------------------------
    // Identifiable implementation
    // ---------------------------

    @Override
    @Transient
    @XmlTransient
    public Integer getId() {
        return getTagId();
    }

    @Override
    public void setId(Integer tagId) {
        setTagId(tagId);
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return isTagIdSet();
    }

    // -------------------------------
    // Getter & Setter
    // -------------------------------

    // -- [tagId] ------------------------

    @Column(name = "tag_id", precision = 10)
    @GeneratedValue
    @Id
    public Integer getTagId() {
        return tagId;
    }

    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    @Transient
    public boolean isTagIdSet() {
        return tagId != null;
    }

    // -- [tagTitle] ------------------------

    @Size(max = 45)
    @Column(name = "tag_title", length = 45)
    public String getTagTitle() {
        return tagTitle;
    }

    public void setTagTitle(String tagTitle) {
        this.tagTitle = tagTitle;
    }

    // -- [tagPriority] ------------------------

    @Column(name = "tag_priority", precision = 10)
    public Integer getTagPriority() {
        return tagPriority;
    }

    public void setTagPriority(Integer tagPriority) {
        this.tagPriority = tagPriority;
    }

    // -- [tagType] ------------------------

    @Column(name = "tag_type", precision = 5)
    public Integer getTagType() {
        return tagType;
    }

    public void setTagType(Integer tagType) {
        this.tagType = tagType;
    }

    // -- [tagDesc] ------------------------

    @Size(max = 512)
    @Column(name = "tag_desc", length = 512)
    public String getTagDesc() {
        return tagDesc;
    }

    public void setTagDesc(String tagDesc) {
        this.tagDesc = tagDesc;
    }

    // -- [tagUrl] ------------------------

    @Size(max = 45)
   // @URL
    @Column(name = "tag_url", length = 45)
    public String getTagUrl() {
        return tagUrl;
    }

    public void setTagUrl(String tagUrl) {
        this.tagUrl = tagUrl;
    }

    // -- [creationDate] ------------------------

    @Column(name = "creation_date", length = 19)
    @Temporal(TIMESTAMP)
    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    // -- [updationDate] ------------------------

    @Column(name = "updation_date", length = 19)
    @Temporal(TIMESTAMP)
    public Date getUpdationDate() {
        return updationDate;
    }

    public void setUpdationDate(Date updationDate) {
        this.updationDate = updationDate;
    }

    // -- [isActive] ------------------------

    @Column(name = "is_active", precision = 5)
    public Integer getIsActive() {
        return isActive;
    }

    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

    // -- [tagStatus] ------------------------

    @Column(name = "tag_status", precision = 5)
    public Integer getTagStatus() {
        return tagStatus;
    }

    public void setTagStatus(Integer tagStatus) {
        this.tagStatus = tagStatus;
    }

    /**
     * Set the default values.
     */
    public void initDefaultValues() {
    }

    /**
     * equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof TdTag && hashCode() == other.hashCode());
    }

    private PersistableHashBuilder persistableHashBuilder = new PersistableHashBuilder();

    @Override
    public int hashCode() {
        return persistableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this TdTag instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add("tagId", getTagId()) //
                .add("tagTitle", getTagTitle()) //
                .add("tagPriority", getTagPriority()) //
                .add("tagType", getTagType()) //
                .add("tagDesc", getTagDesc()) //
                .add("tagUrl", getTagUrl()) //
                .add("creationDate", getCreationDate()) //
                .add("updationDate", getUpdationDate()) //
                .add("isActive", getIsActive()) //
                .add("tagStatus", getTagStatus()) //
                .toString();
    }

    @PrePersist
    protected void prePersist() {
        setCreationDate(new Date());
    }
}