/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity.e.vm.java
 */
package com.app.mpadmin.domain;

import static javax.persistence.TemporalType.TIMESTAMP;
import static org.hibernate.annotations.CacheConcurrencyStrategy.NONSTRICT_READ_WRITE;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlTransient;
import org.apache.log4j.Logger;
import org.hibernate.annotations.Cache;
import com.app.mpadmin.domain.PersistableHashBuilder;
import com.google.common.base.Objects;

@Entity
@Table(name = "td_tag_grp")
@Cache(usage = NONSTRICT_READ_WRITE)
public class TdTagGrp implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(TdTagGrp.class);

    // Raw attributes
    private Integer tagGrpId; // pk
    private Integer referenceId;
    private Date creationDate;
    private Date updationDate;
    private Integer isActive;
    private Integer tagGrpStatus;
    private Integer referenceType;

    // ---------------------------
    // Constructors
    // ---------------------------

    public TdTagGrp() {
    }

    public TdTagGrp(Integer primaryKey) {
        setId(primaryKey);
    }

    // ---------------------------
    // Identifiable implementation
    // ---------------------------

    @Override
    @Transient
    @XmlTransient
    public Integer getId() {
        return getTagGrpId();
    }

    @Override
    public void setId(Integer tagGrpId) {
        setTagGrpId(tagGrpId);
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return isTagGrpIdSet();
    }

    // -------------------------------
    // Getter & Setter
    // -------------------------------

    // -- [tagGrpId] ------------------------

    @Column(name = "tag_grp_id", precision = 10)
    @GeneratedValue
    @Id
    public Integer getTagGrpId() {
        return tagGrpId;
    }

    public void setTagGrpId(Integer tagGrpId) {
        this.tagGrpId = tagGrpId;
    }

    @Transient
    public boolean isTagGrpIdSet() {
        return tagGrpId != null;
    }

    // -- [referenceId] ------------------------

    @Column(name = "reference_id", precision = 10)
    public Integer getReferenceId() {
        return referenceId;
    }

    public void setReferenceId(Integer referenceId) {
        this.referenceId = referenceId;
    }

    // -- [creationDate] ------------------------

    @Column(name = "creation_date", length = 19)
    @Temporal(TIMESTAMP)
    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    // -- [updationDate] ------------------------

    @Column(name = "updation_date", length = 19)
    @Temporal(TIMESTAMP)
    public Date getUpdationDate() {
        return updationDate;
    }

    public void setUpdationDate(Date updationDate) {
        this.updationDate = updationDate;
    }

    // -- [isActive] ------------------------

    @Column(name = "is_active", precision = 5)
    public Integer getIsActive() {
        return isActive;
    }

    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

    // -- [tagGrpStatus] ------------------------

    @Column(name = "tag_grp_status", precision = 5)
    public Integer getTagGrpStatus() {
        return tagGrpStatus;
    }

    public void setTagGrpStatus(Integer tagGrpStatus) {
        this.tagGrpStatus = tagGrpStatus;
    }

    // -- [referenceType] ------------------------

    @Column(name = "reference_type", precision = 5)
    public Integer getReferenceType() {
        return referenceType;
    }

    public void setReferenceType(Integer referenceType) {
        this.referenceType = referenceType;
    }

    /**
     * Set the default values.
     */
    public void initDefaultValues() {
    }

    /**
     * equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof TdTagGrp && hashCode() == other.hashCode());
    }

    private PersistableHashBuilder persistableHashBuilder = new PersistableHashBuilder();

    @Override
    public int hashCode() {
        return persistableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this TdTagGrp instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add("tagGrpId", getTagGrpId()) //
                .add("referenceId", getReferenceId()) //
                .add("creationDate", getCreationDate()) //
                .add("updationDate", getUpdationDate()) //
                .add("isActive", getIsActive()) //
                .add("tagGrpStatus", getTagGrpStatus()) //
                .add("referenceType", getReferenceType()) //
                .toString();
    }

    @PrePersist
    protected void prePersist() {
        setCreationDate(new Date());
    }
}