/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity_.e.vm.java
 */
package com.app.mpadmin.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(TdTagGrpTagMapping.class)
public abstract class TdTagGrpTagMapping_ {

    // Raw attributes
    public static volatile SingularAttribute<TdTagGrpTagMapping, Integer> grpTagMappingId;
    public static volatile SingularAttribute<TdTagGrpTagMapping, Integer> tagGrpId;
    public static volatile SingularAttribute<TdTagGrpTagMapping, Integer> tagId;
}