/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity_.e.vm.java
 */
package com.app.mpadmin.domain;

import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import com.app.mpadmin.domain.TdRole;

@StaticMetamodel(TdUserAuth.class)
public abstract class TdUserAuth_ {

    // Raw attributes
    public static volatile SingularAttribute<TdUserAuth, Integer> userId;
    public static volatile SingularAttribute<TdUserAuth, String> username;
    public static volatile SingularAttribute<TdUserAuth, String> email;
    public static volatile SingularAttribute<TdUserAuth, String> userpassword;
    public static volatile SingularAttribute<TdUserAuth, Integer> isActive;
    public static volatile SingularAttribute<TdUserAuth, Date> creationDate;
    public static volatile SingularAttribute<TdUserAuth, Date> updationDate;

    // Technical attributes for query by example
    public static volatile SingularAttribute<TdUserAuth, Integer> roleId;

    // Many to one
    public static volatile SingularAttribute<TdUserAuth, TdRole> role;
}