/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity_.e.vm.java
 */
package com.app.mpadmin.domain;

import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import com.app.mpadmin.domain.TdUserAuth;

@StaticMetamodel(TdUserDetail.class)
public abstract class TdUserDetail_ {

    // Raw attributes
    public static volatile SingularAttribute<TdUserDetail, Integer> userDetailsId;
    public static volatile SingularAttribute<TdUserDetail, String> firstname;
    public static volatile SingularAttribute<TdUserDetail, String> lastname;
    public static volatile SingularAttribute<TdUserDetail, Integer> isActive;
    public static volatile SingularAttribute<TdUserDetail, Date> dob;
    public static volatile SingularAttribute<TdUserDetail, Integer> phone;
    public static volatile SingularAttribute<TdUserDetail, String> interest;
    public static volatile SingularAttribute<TdUserDetail, Date> creationDate;
    public static volatile SingularAttribute<TdUserDetail, Date> updationDate;
    public static volatile SingularAttribute<TdUserDetail, Integer> credit;

    // Technical attributes for query by example
    public static volatile SingularAttribute<TdUserDetail, Integer> userId;

    // Many to one
    public static volatile SingularAttribute<TdUserDetail, TdUserAuth> user;
}