/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity_.e.vm.java
 */
package com.app.mpadmin.domain;

import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import com.app.mpadmin.domain.TdUserActivity;

@StaticMetamodel(TdUserActivityEvent.class)
public abstract class TdUserActivityEvent_ {

    // Raw attributes
    public static volatile SingularAttribute<TdUserActivityEvent, Integer> userActivityEventId;
    public static volatile SingularAttribute<TdUserActivityEvent, String> userActivityName;
    public static volatile SingularAttribute<TdUserActivityEvent, String> userEventName;
    public static volatile SingularAttribute<TdUserActivityEvent, String> userEventDesc;
    public static volatile SingularAttribute<TdUserActivityEvent, Date> creationDate;
    public static volatile SingularAttribute<TdUserActivityEvent, Date> updationDate;

    // Technical attributes for query by example
    public static volatile SingularAttribute<TdUserActivityEvent, Integer> userActivityId;

    // Many to one
    public static volatile SingularAttribute<TdUserActivityEvent, TdUserActivity> userActivity;
}