/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity.e.vm.java
 */
package com.app.mpadmin.domain;

import static org.hibernate.annotations.CacheConcurrencyStrategy.NONSTRICT_READ_WRITE;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlTransient;
import org.apache.log4j.Logger;
import org.hibernate.annotations.Cache;
import com.app.mpadmin.domain.PersistableHashBuilder;
import com.google.common.base.Objects;

@Entity
@Table(name = "temp_td_submodel_year_mapping")
@Cache(usage = NONSTRICT_READ_WRITE)
public class TempTdSubmodelYearMapping implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(TempTdSubmodelYearMapping.class);

    // Raw attributes
    private Integer submodelYearMappingId; // pk
    private Integer makeSubmodelId; // not null
    private Integer modelLaunchYear; // not null
    private Integer modelEndYear; // not null

    // ---------------------------
    // Constructors
    // ---------------------------

    public TempTdSubmodelYearMapping() {
    }

    public TempTdSubmodelYearMapping(Integer primaryKey) {
        setId(primaryKey);
    }

    // ---------------------------
    // Identifiable implementation
    // ---------------------------

    @Override
    @Transient
    @XmlTransient
    public Integer getId() {
        return getSubmodelYearMappingId();
    }

    @Override
    public void setId(Integer submodelYearMappingId) {
        setSubmodelYearMappingId(submodelYearMappingId);
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return isSubmodelYearMappingIdSet();
    }

    // -------------------------------
    // Getter & Setter
    // -------------------------------

    // -- [submodelYearMappingId] ------------------------

    @NotNull
    @Column(name = "submodel_year_mapping_id", precision = 10)
    @Id
    public Integer getSubmodelYearMappingId() {
        return submodelYearMappingId;
    }

    public void setSubmodelYearMappingId(Integer submodelYearMappingId) {
        this.submodelYearMappingId = submodelYearMappingId;
    }

    @Transient
    public boolean isSubmodelYearMappingIdSet() {
        return submodelYearMappingId != null;
    }

    // -- [makeSubmodelId] ------------------------

    @NotNull
    @Column(name = "make_submodel_id", nullable = false, precision = 5)
    public Integer getMakeSubmodelId() {
        return makeSubmodelId;
    }

    public void setMakeSubmodelId(Integer makeSubmodelId) {
        this.makeSubmodelId = makeSubmodelId;
    }

    // -- [modelLaunchYear] ------------------------

    @NotNull
    @Column(name = "model_launch_year", nullable = false, precision = 5)
    public Integer getModelLaunchYear() {
        return modelLaunchYear;
    }

    public void setModelLaunchYear(Integer modelLaunchYear) {
        this.modelLaunchYear = modelLaunchYear;
    }

    // -- [modelEndYear] ------------------------

    @NotNull
    @Column(name = "model_end_year", nullable = false, precision = 5)
    public Integer getModelEndYear() {
        return modelEndYear;
    }

    public void setModelEndYear(Integer modelEndYear) {
        this.modelEndYear = modelEndYear;
    }

    /**
     * Set the default values.
     */
    public void initDefaultValues() {
    }

    /**
     * equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof TempTdSubmodelYearMapping && hashCode() == other.hashCode());
    }

    private PersistableHashBuilder persistableHashBuilder = new PersistableHashBuilder();

    @Override
    public int hashCode() {
        return persistableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this TempTdSubmodelYearMapping instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add("submodelYearMappingId", getSubmodelYearMappingId()) //
                .add("makeSubmodelId", getMakeSubmodelId()) //
                .add("modelLaunchYear", getModelLaunchYear()) //
                .add("modelEndYear", getModelEndYear()) //
                .toString();
    }
}