/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/repository/RepositoryImpl.e.vm.java
 */
package com.app.mpadmin.repository;

import javax.inject.Inject;

import org.apache.log4j.Logger;

import javax.inject.Named;
import javax.inject.Singleton;

import com.app.mpadmin.dao.support.GenericDao;
import com.app.mpadmin.repository.support.RepositoryImpl;
import com.app.mpadmin.domain.AuthPermission;
import com.app.mpadmin.dao.AuthPermissionDao;

/**
 * Default implementation of the {@link AuthPermissionRepository} interface.
 * Note: you may use multiple DAO from this layer.
 * @see AuthPermissionRepository
 */
@Named("authPermissionRepository")
@Singleton
public class AuthPermissionRepositoryImpl extends RepositoryImpl<AuthPermission, Integer> implements AuthPermissionRepository {

    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(AuthPermissionRepositoryImpl.class);

    protected AuthPermissionDao authPermissionDao;

    @Inject
    public void setAuthPermissionDao(AuthPermissionDao authPermissionDao) {
        this.authPermissionDao = authPermissionDao;
    }

    /**
     * Dao getter used by the {@link RepositoryImpl}.
     */
    @Override
    public GenericDao<AuthPermission, Integer> getDao() {
        return authPermissionDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthPermission getNew() {
        return new AuthPermission();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthPermission getNewWithDefaults() {
        AuthPermission result = getNew();
        result.initDefaultValues();
        return result;
    }

}