/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/repository/RepositoryImpl.e.vm.java
 */
package com.app.mpadmin.repository;

import javax.inject.Inject;

import org.apache.log4j.Logger;

import javax.inject.Named;
import javax.inject.Singleton;

import com.app.mpadmin.dao.support.GenericDao;
import com.app.mpadmin.repository.support.RepositoryImpl;
import com.app.mpadmin.domain.TdMake;
import com.app.mpadmin.dao.TdMakeDao;

/**
 * Default implementation of the {@link TdMakeRepository} interface.
 * Note: you may use multiple DAO from this layer.
 * @see TdMakeRepository
 */
@Named("tdMakeRepository")
@Singleton
public class TdMakeRepositoryImpl extends RepositoryImpl<TdMake, Integer> implements TdMakeRepository {

    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(TdMakeRepositoryImpl.class);

    protected TdMakeDao tdMakeDao;

    @Inject
    public void setTdMakeDao(TdMakeDao tdMakeDao) {
        this.tdMakeDao = tdMakeDao;
    }

    /**
     * Dao getter used by the {@link RepositoryImpl}.
     */
    @Override
    public GenericDao<TdMake, Integer> getDao() {
        return tdMakeDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TdMake getNew() {
        return new TdMake();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TdMake getNewWithDefaults() {
        TdMake result = getNew();
        result.initDefaultValues();
        return result;
    }

}