/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/repository/RepositoryImpl.e.vm.java
 */
package com.app.mpadmin.repository;

import javax.inject.Inject;

import org.apache.log4j.Logger;

import javax.inject.Named;
import javax.inject.Singleton;

import com.app.mpadmin.dao.support.GenericDao;
import com.app.mpadmin.repository.support.RepositoryImpl;
import com.app.mpadmin.domain.TdOrder;
import com.app.mpadmin.dao.TdOrderDao;

/**
 * Default implementation of the {@link TdOrderRepository} interface.
 * Note: you may use multiple DAO from this layer.
 * @see TdOrderRepository
 */
@Named("tdOrderRepository")
@Singleton
public class TdOrderRepositoryImpl extends RepositoryImpl<TdOrder, Integer> implements TdOrderRepository {

    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(TdOrderRepositoryImpl.class);

    protected TdOrderDao tdOrderDao;

    @Inject
    public void setTdOrderDao(TdOrderDao tdOrderDao) {
        this.tdOrderDao = tdOrderDao;
    }

    /**
     * Dao getter used by the {@link RepositoryImpl}.
     */
    @Override
    public GenericDao<TdOrder, Integer> getDao() {
        return tdOrderDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TdOrder getNew() {
        return new TdOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TdOrder getNewWithDefaults() {
        TdOrder result = getNew();
        result.initDefaultValues();
        return result;
    }

}