/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/repository/Repository.e.vm.java
 */
package com.app.mpadmin.repository;

import com.app.mpadmin.domain.TdProductBrand;
import com.app.mpadmin.repository.support.Repository;

/**
 * The TdProductBrandRepository is a data-centric service for the {@link TdProductBrand} entity.
 * It provides the expected methods to get/delete a {@link TdProductBrand} instance
 * plus some methods to perform searches.
 * <p>
 * Search logic is driven by 2 kinds of parameters: a {@link TdProductBrand} instance used
 * as a properties holder against which the search will be performed and a {@link SearchParameters}
 * instance from where you can control your search options including the usage
 * of named queries.
 */
public interface TdProductBrandRepository extends Repository<TdProductBrand, Integer> {

    /**
     * Return the persistent instance of {@link TdProductBrand} with the given unique property value seoUrl,
     * or null if there is no such persistent instance.
     *
     * @param seoUrl the unique value
     * @return the corresponding {@link TdProductBrand} persistent instance or null
     */
    TdProductBrand getBySeoUrl(String seoUrl);

    /**
     * Delete a {@link TdProductBrand} using the unique column seoUrl
     *
     * @param seoUrl the unique value
     */
    void deleteBySeoUrl(String seoUrl);
}