/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/repository/RepositoryImpl.e.vm.java
 */
package com.app.mpadmin.repository;

import javax.inject.Inject;

import org.apache.log4j.Logger;

import javax.inject.Named;
import javax.inject.Singleton;

import com.app.mpadmin.dao.support.GenericDao;
import com.app.mpadmin.repository.support.RepositoryImpl;
import com.app.mpadmin.domain.TdProduct;
import com.app.mpadmin.dao.TdProductDao;

/**
 * Default implementation of the {@link TdProductRepository} interface.
 * Note: you may use multiple DAO from this layer.
 * @see TdProductRepository
 */
@Named("tdProductRepository")
@Singleton
public class TdProductRepositoryImpl extends RepositoryImpl<TdProduct, Integer> implements TdProductRepository {

    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(TdProductRepositoryImpl.class);

    protected TdProductDao tdProductDao;

    @Inject
    public void setTdProductDao(TdProductDao tdProductDao) {
        this.tdProductDao = tdProductDao;
    }

    /**
     * Dao getter used by the {@link RepositoryImpl}.
     */
    @Override
    public GenericDao<TdProduct, Integer> getDao() {
        return tdProductDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TdProduct getNew() {
        return new TdProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TdProduct getNewWithDefaults() {
        TdProduct result = getNew();
        result.initDefaultValues();
        return result;
    }

}