/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/repository/RepositoryImpl.e.vm.java
 */
package com.app.mpadmin.repository;

import javax.inject.Inject;

import org.apache.log4j.Logger;

import javax.inject.Named;
import javax.inject.Singleton;

import com.app.mpadmin.dao.support.GenericDao;
import com.app.mpadmin.repository.support.RepositoryImpl;
import com.app.mpadmin.domain.TempTdTagGrpTagMapping;
import com.app.mpadmin.domain.TempTdTagGrpTagMappingPk;
import com.app.mpadmin.dao.TempTdTagGrpTagMappingDao;

/**
 * Default implementation of the {@link TempTdTagGrpTagMappingRepository} interface.
 * Note: you may use multiple DAO from this layer.
 * @see TempTdTagGrpTagMappingRepository
 */
@Named("tempTdTagGrpTagMappingRepository")
@Singleton
public class TempTdTagGrpTagMappingRepositoryImpl extends RepositoryImpl<TempTdTagGrpTagMapping, TempTdTagGrpTagMappingPk> implements
        TempTdTagGrpTagMappingRepository {

    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(TempTdTagGrpTagMappingRepositoryImpl.class);

    protected TempTdTagGrpTagMappingDao tempTdTagGrpTagMappingDao;

    @Inject
    public void setTempTdTagGrpTagMappingDao(TempTdTagGrpTagMappingDao tempTdTagGrpTagMappingDao) {
        this.tempTdTagGrpTagMappingDao = tempTdTagGrpTagMappingDao;
    }

    /**
     * Dao getter used by the {@link RepositoryImpl}.
     */
    @Override
    public GenericDao<TempTdTagGrpTagMapping, TempTdTagGrpTagMappingPk> getDao() {
        return tempTdTagGrpTagMappingDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TempTdTagGrpTagMapping getNew() {
        return new TempTdTagGrpTagMapping();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TempTdTagGrpTagMapping getNewWithDefaults() {
        TempTdTagGrpTagMapping result = getNew();
        result.initDefaultValues();
        return result;
    }

}