/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/converter/EntityConverter.e.vm.java
 */
package com.app.mpadmin.web.converter.domain;

import javax.inject.Inject;
import org.springframework.stereotype.Component;
import com.app.mpadmin.domain.TdUserAddress;
import com.app.mpadmin.repository.TdUserAddressRepository;
import com.app.mpadmin.web.converter.GenericJsfConverter;

/**
 * Responsible for creating TdUserAddress JSF converters.
 * Each converter provides a 'print' method to convert an entity instance to a friendly string representation (readable by humans...).
 */
@Component
public class TdUserAddressConverter extends GenericJsfConverter<TdUserAddress, Integer> {
    @Inject
    public TdUserAddressConverter(TdUserAddressRepository tdUserAddressRepository) {
        super(tdUserAddressRepository, Integer.class);
    }

    @Override
    public String print(TdUserAddress tdUserAddress) {
        return tdUserAddress == null ? "" : "" + tdUserAddress.getAddress1() + "/" + tdUserAddress.getAddress2();
    }
}