/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/dao/DaoImplIT.e.vm.java
 */
package com.app.mpadmin.dao;

import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.apache.log4j.Logger;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.*;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.app.mpadmin.domain.TdCountry;
import com.app.mpadmin.repository.TdCountryGenerator;
import com.app.mpadmin.dao.TdCountryDao;

/**
 * Integration test on TdCountryDaoImpl
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class TdCountryDaoImplIT {
    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(TdCountryDaoImplIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private TdCountryDao tdCountryDao;

    @Inject
    private TdCountryGenerator tdCountryGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        TdCountry tdCountry = tdCountryGenerator.getTdCountry();

        // add it to a Set before saving (force equals/hashcode)
        Set<TdCountry> set = newHashSet(tdCountry, tdCountry);
        assertThat(set).hasSize(1);

        tdCountryDao.save(tdCountry);
        entityManager.flush();

        // reload it from cache and check equality
        TdCountry model = new TdCountry();
        model.setCountryId(tdCountry.getCountryId());
        assertThat(tdCountry).isEqualTo(tdCountryDao.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // since you use a business key, equality must be preserved.
        assertThat(tdCountry).isEqualTo(tdCountryDao.get(model));
    }
}