/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/dao/DaoImplIT.e.vm.java
 */
package com.app.mpadmin.dao;

import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.apache.log4j.Logger;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.*;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.app.mpadmin.domain.TdProductBrand;
import com.app.mpadmin.repository.TdProductBrandGenerator;
import com.app.mpadmin.dao.TdProductBrandDao;

/**
 * Integration test on TdProductBrandDaoImpl
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class TdProductBrandDaoImplIT {
    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(TdProductBrandDaoImplIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private TdProductBrandDao tdProductBrandDao;

    @Inject
    private TdProductBrandGenerator tdProductBrandGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        TdProductBrand tdProductBrand = tdProductBrandGenerator.getTdProductBrand();

        // add it to a Set before saving (force equals/hashcode)
        Set<TdProductBrand> set = newHashSet(tdProductBrand, tdProductBrand);
        assertThat(set).hasSize(1);

        tdProductBrandDao.save(tdProductBrand);
        entityManager.flush();

        // reload it from cache and check equality
        TdProductBrand model = new TdProductBrand();
        model.setProductBrandId(tdProductBrand.getProductBrandId());
        assertThat(tdProductBrand).isEqualTo(tdProductBrandDao.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // since you use a business key, equality must be preserved.
        assertThat(tdProductBrand).isEqualTo(tdProductBrandDao.get(model));
    }
}