/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/dao/DaoImplIT.e.vm.java
 */
package com.app.mpadmin.dao;

import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.apache.log4j.Logger;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.*;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.app.mpadmin.domain.TdSubmodelYearMapping;
import com.app.mpadmin.repository.TdSubmodelYearMappingGenerator;
import com.app.mpadmin.dao.TdSubmodelYearMappingDao;

/**
 * Integration test on TdSubmodelYearMappingDaoImpl
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class TdSubmodelYearMappingDaoImplIT {
    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(TdSubmodelYearMappingDaoImplIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private TdSubmodelYearMappingDao tdSubmodelYearMappingDao;

    @Inject
    private TdSubmodelYearMappingGenerator tdSubmodelYearMappingGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        TdSubmodelYearMapping tdSubmodelYearMapping = tdSubmodelYearMappingGenerator.getTdSubmodelYearMapping();

        // add it to a Set before saving (force equals/hashcode)
        Set<TdSubmodelYearMapping> set = newHashSet(tdSubmodelYearMapping, tdSubmodelYearMapping);
        assertThat(set).hasSize(1);

        tdSubmodelYearMappingDao.save(tdSubmodelYearMapping);
        entityManager.flush();

        // reload it from cache and check equality
        TdSubmodelYearMapping model = new TdSubmodelYearMapping();
        model.setSubmodelYearMappingId(tdSubmodelYearMapping.getSubmodelYearMappingId());
        assertThat(tdSubmodelYearMapping).isEqualTo(tdSubmodelYearMappingDao.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // since you use a business key, equality must be preserved.
        assertThat(tdSubmodelYearMapping).isEqualTo(tdSubmodelYearMappingDao.get(model));
    }
}