/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/dao/DaoImplIT.e.vm.java
 */
package com.app.mpadmin.dao;

import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.apache.log4j.Logger;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.*;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.app.mpadmin.domain.TdTopic;
import com.app.mpadmin.repository.TdTopicGenerator;
import com.app.mpadmin.dao.TdTopicDao;

/**
 * Integration test on TdTopicDaoImpl
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class TdTopicDaoImplIT {
    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(TdTopicDaoImplIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private TdTopicDao tdTopicDao;

    @Inject
    private TdTopicGenerator tdTopicGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        TdTopic tdTopic = tdTopicGenerator.getTdTopic();

        // add it to a Set before saving (force equals/hashcode)
        Set<TdTopic> set = newHashSet(tdTopic, tdTopic);
        assertThat(set).hasSize(1);

        tdTopicDao.save(tdTopic);
        entityManager.flush();

        // reload it from cache and check equality
        TdTopic model = new TdTopic();
        model.setTopicId(tdTopic.getTopicId());
        assertThat(tdTopic).isEqualTo(tdTopicDao.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(tdTopic.getId()).isEqualTo(tdTopicDao.get(model).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(tdTopic).isNotEqualTo(tdTopicDao.get(model));
    }
}