/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/dao/DaoImplIT.e.vm.java
 */
package com.app.mpadmin.dao;

import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.apache.log4j.Logger;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.*;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.app.mpadmin.domain.TdUserActivity;
import com.app.mpadmin.repository.TdUserActivityGenerator;
import com.app.mpadmin.dao.TdUserActivityDao;

/**
 * Integration test on TdUserActivityDaoImpl
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class TdUserActivityDaoImplIT {
    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(TdUserActivityDaoImplIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private TdUserActivityDao tdUserActivityDao;

    @Inject
    private TdUserActivityGenerator tdUserActivityGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        TdUserActivity tdUserActivity = tdUserActivityGenerator.getTdUserActivity();

        // add it to a Set before saving (force equals/hashcode)
        Set<TdUserActivity> set = newHashSet(tdUserActivity, tdUserActivity);
        assertThat(set).hasSize(1);

        tdUserActivityDao.save(tdUserActivity);
        entityManager.flush();

        // reload it from cache and check equality
        TdUserActivity model = new TdUserActivity();
        model.setUserActivityId(tdUserActivity.getUserActivityId());
        assertThat(tdUserActivity).isEqualTo(tdUserActivityDao.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(tdUserActivity.getId()).isEqualTo(tdUserActivityDao.get(model).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(tdUserActivity).isNotEqualTo(tdUserActivityDao.get(model));
    }
}