/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/LazyDataModel.e.vm.java
 */
package com.app.mpadmin.web.domain;

import java.util.List;
import java.util.Map;
import javax.inject.Inject;

import org.primefaces.model.SortOrder;

import com.app.mpadmin.dao.support.SearchParameters;
import com.app.mpadmin.domain.AuthUser;
import com.app.mpadmin.repository.AuthUserRepository;
import com.app.mpadmin.web.domain.support.GenericLazyDataModel;

/**
 * Provides server-side pagination for search.
 *
 * @see http://jira.springframework.org/browse/SWF-1224 to avoid instanciate it as a var from your flow 
 */
public class AuthUserLazyDataModel extends GenericLazyDataModel<AuthUser> {
    private static final long serialVersionUID = 1L;

    @Inject
    transient private AuthUserRepository authUserRepository;
    @Inject
    transient private AuthUserSearchForm authUserSearchForm;

    /**
     * Prepare the search parameters and call the authUserRepository finder.
     * Automatically called by PrimeFaces component.
     */
    @Override
    public List<AuthUser> load(int first, int pageSize, String sortField, SortOrder sortOrder, Map<String, String> filters) {
        SearchParameters sp = authUserSearchForm.getSearchParameters();

        // ranges
        sp.clearRanges();
        sp.addRange(authUserSearchForm.getLastLoginRange());
        sp.addRange(authUserSearchForm.getDateJoinedRange());

        // property selectors
        sp.clearPropertySelectors();
        sp.addPropertySelector(authUserSearchForm.getIsStaffSelector());
        sp.addPropertySelector(authUserSearchForm.getIsActiveSelector());
        sp.addPropertySelector(authUserSearchForm.getIsSuperuserSelector());

        AuthUser authUser = authUserSearchForm.getAuthUser();
        setRowCount(authUserRepository.findCount(authUser, sp)); // total count so the paginator may display the total number of pages
        populateSearchParameters(sp, first, pageSize, sortField, sortOrder, filters); // load one page of data

        return authUserRepository.find(authUser, sp);
    }
}