/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/Controller.e.vm.java
 */
package com.app.mpadmin.web.domain;

import static com.app.mpadmin.web.util.PrimeFacesUtil.forceClose;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.app.mpadmin.domain.AuthGroupPermissions;
import com.app.mpadmin.repository.AuthGroupPermissionsRepository;
import com.app.mpadmin.web.converter.domain.AuthGroupPermissionsConverter;
import com.app.mpadmin.web.util.MessageUtil;

/**
 * Thin controller layer allowing you to do business validation and other conditional 
 * checks that are easier to implement in Java than in webflow's xml syntax.
 */
@Named
@Singleton
public class AuthGroupPermissionsController {
    private static final long serialVersionUID = 1L;

    @Inject
    private AuthGroupPermissionsRepository authGroupPermissionsRepository;

    @Inject
    private MessageUtil messageUtil;

    @Inject
    private AuthGroupPermissionsConverter authGroupPermissionsConverter;

    public AuthGroupPermissions newIfNull(AuthGroupPermissions authGroupPermissions) {
        if (authGroupPermissions != null) {
            return authGroupPermissions;
        }

        return authGroupPermissionsRepository.getNewWithDefaults();
    }

    public boolean save(AuthGroupPermissions authGroupPermissions) {
        authGroupPermissionsRepository.save(authGroupPermissions);
        messageUtil.info("status_saved_ok", authGroupPermissionsConverter.print(authGroupPermissions));
        return true;
    }

    public boolean saveAndClose(AuthGroupPermissions authGroupPermissions) {
        authGroupPermissionsRepository.save(authGroupPermissions);
        messageUtil.infoDelayed("status_saved_ok", authGroupPermissionsConverter.print(authGroupPermissions));
        forceClose();
        return true;
    }

    public boolean delete(AuthGroupPermissions authGroupPermissions) {
        String infoArg = authGroupPermissionsConverter.print(authGroupPermissions);
        authGroupPermissionsRepository.delete(authGroupPermissions);
        messageUtil.info("status_deleted_ok", infoArg);
        return true;
    }
}