/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/LazyDataModel.e.vm.java
 */
package com.app.mpadmin.web.domain;

import java.util.List;
import java.util.Map;
import javax.inject.Inject;

import org.primefaces.model.SortOrder;

import com.app.mpadmin.dao.support.SearchParameters;
import com.app.mpadmin.domain.TdCountry;
import com.app.mpadmin.repository.TdCountryRepository;
import com.app.mpadmin.web.domain.support.GenericLazyDataModel;

/**
 * Provides server-side pagination for search.
 *
 * @see http://jira.springframework.org/browse/SWF-1224 to avoid instanciate it as a var from your flow 
 */
public class TdCountryLazyDataModel extends GenericLazyDataModel<TdCountry> {
    private static final long serialVersionUID = 1L;

    @Inject
    transient private TdCountryRepository tdCountryRepository;
    @Inject
    transient private TdCountrySearchForm tdCountrySearchForm;

    List<TdCountry> datasource;

        @Override
        public TdCountry getRowData(String rowKey) {
            for(TdCountry tdCountry : datasource) {
                if(tdCountry.getCountryId().equals(rowKey))
                    return tdCountry;
            }

            return null;
        }

        @Override
        public Object getRowKey(TdCountry tdCountry)
        {
             return tdCountry.getCountryId();
        }

    /**
     * Prepare the search parameters and call the tdCountryRepository finder.
     * Automatically called by PrimeFaces component.
     */
    @Override
    public List<TdCountry> load(int first, int pageSize, String sortField, SortOrder sortOrder, Map<String, String> filters) {
        SearchParameters sp = tdCountrySearchForm.getSearchParameters();

        // ranges
        sp.clearRanges();
        sp.addRange(tdCountrySearchForm.getImportanceRange());
        sp.addRange(tdCountrySearchForm.getCountryCodeRange());
        sp.addRange(tdCountrySearchForm.getCountryCode2Range());
        sp.addRange(tdCountrySearchForm.getIsdCodeRange());
        sp.addRange(tdCountrySearchForm.getUpdationDateRange());
        sp.addRange(tdCountrySearchForm.getCountryIdRange());
        TdCountry tdCountry = tdCountrySearchForm.getTdCountry();
        setRowCount(tdCountryRepository.findCount(tdCountry, sp)); // total count so the paginator may display the total number of pages
        populateSearchParameters(sp, first, pageSize, sortField, sortOrder, filters); // load one page of data
        datasource = tdCountryRepository.find(tdCountry, sp);
        return  datasource;
    }
}