/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/LazyDataModel.e.vm.java
 */
package com.app.mpadmin.web.domain;

import java.util.List;
import java.util.Map;
import javax.inject.Inject;

import org.primefaces.model.SortOrder;

import com.app.mpadmin.dao.support.SearchParameters;
import com.app.mpadmin.domain.TdMakeModel;
import com.app.mpadmin.repository.TdMakeModelRepository;
import com.app.mpadmin.web.domain.support.GenericLazyDataModel;

/**
 * Provides server-side pagination for search.
 *
 * @see http://jira.springframework.org/browse/SWF-1224 to avoid instanciate it as a var from your flow 
 */
public class TdMakeModelLazyDataModel extends GenericLazyDataModel<TdMakeModel> {
    private static final long serialVersionUID = 1L;

    @Inject
    transient private TdMakeModelRepository tdMakeModelRepository;
    @Inject
    transient private TdMakeModelSearchForm tdMakeModelSearchForm;

    /**
     * Prepare the search parameters and call the tdMakeModelRepository finder.
     * Automatically called by PrimeFaces component.
     */
    @Override
    public List<TdMakeModel> load(int first, int pageSize, String sortField, SortOrder sortOrder, Map<String, String> filters) {
        SearchParameters sp = tdMakeModelSearchForm.getSearchParameters();

        // ranges
        sp.clearRanges();
        // sp.addRange(tdMakeModelSearchForm.getMakeIdRange());
        sp.addRange(tdMakeModelSearchForm.getIsActiveRange());
        sp.addRange(tdMakeModelSearchForm.getModelLaunchYearRange());
        sp.addRange(tdMakeModelSearchForm.getFuelTypeRange());
        sp.addRange(tdMakeModelSearchForm.getTransmissionTypeRange());
        sp.addRange(tdMakeModelSearchForm.getWheeldriveTypeRange());
        sp.addRange(tdMakeModelSearchForm.getEngineCapacityRange());
        sp.addRange(tdMakeModelSearchForm.getBodyTypeRange());
        sp.addRange(tdMakeModelSearchForm.getDoorCountRange());
        sp.addRange(tdMakeModelSearchForm.getGearCountRange());
        sp.addRange(tdMakeModelSearchForm.getFuelDeliveryRange());
        sp.addRange(tdMakeModelSearchForm.getValvesCountRange());
        sp.addRange(tdMakeModelSearchForm.getBhpRange());
        sp.addRange(tdMakeModelSearchForm.getTorqueRange());
        sp.addRange(tdMakeModelSearchForm.getMakemodelStatusRange());
        sp.addRange(tdMakeModelSearchForm.getUpdationDateRange());
        
        // entity selectors
        sp.clearEntitySelectors();
        sp.addEntitySelector(tdMakeModelSearchForm.getMakeSelector());
        
        TdMakeModel tdMakeModel = tdMakeModelSearchForm.getTdMakeModel();
        setRowCount(tdMakeModelRepository.findCount(tdMakeModel, sp)); // total count so the paginator may display the total number of pages
        populateSearchParameters(sp, first, pageSize, sortField, sortOrder, filters); // load one page of data

        return tdMakeModelRepository.find(tdMakeModel, sp);
    }
}