/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/Controller.e.vm.java
 */
package com.app.mpadmin.web.domain;

import static com.app.mpadmin.web.util.PrimeFacesUtil.forceClose;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.app.mpadmin.domain.TdMake;
import com.app.mpadmin.repository.TdMakeRepository;
import com.app.mpadmin.web.converter.domain.TdMakeConverter;
import com.app.mpadmin.web.util.MessageUtil;

/**
 * Thin controller layer allowing you to do business validation and other conditional 
 * checks that are easier to implement in Java than in webflow's xml syntax.
 */
@Named
@Singleton
public class TdMakeController {
    private static final long serialVersionUID = 1L;

    @Inject
    private TdMakeRepository tdMakeRepository;

    @Inject
    private MessageUtil messageUtil;

    @Inject
    private TdMakeConverter tdMakeConverter;

    public TdMake newIfNull(TdMake tdMake) {
        if (tdMake != null) {
            return tdMake;
        }

        return tdMakeRepository.getNewWithDefaults();
    }

    public boolean save(TdMake tdMake) {
        tdMakeRepository.save(tdMake);
        messageUtil.info("status_saved_ok", tdMakeConverter.print(tdMake));
        return true;
    }

    public boolean saveAndClose(TdMake tdMake) {
        tdMakeRepository.save(tdMake);
        messageUtil.infoDelayed("status_saved_ok", tdMakeConverter.print(tdMake));
        forceClose();
        return true;
    }

    public boolean delete(TdMake tdMake) {
        String infoArg = tdMakeConverter.print(tdMake);
        tdMakeRepository.delete(tdMake);
        messageUtil.info("status_deleted_ok", infoArg);
        return true;
    }
}