/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/LazyDataModel.e.vm.java
 */
package com.app.mpadmin.web.domain;

import java.util.List;
import java.util.Map;
import javax.inject.Inject;

import org.primefaces.model.SortOrder;

import com.app.mpadmin.dao.support.SearchParameters;
import com.app.mpadmin.domain.TdMetro;
import com.app.mpadmin.repository.TdMetroRepository;
import com.app.mpadmin.web.domain.support.GenericLazyDataModel;

/**
 * Provides server-side pagination for search.
 *
 * @see http://jira.springframework.org/browse/SWF-1224 to avoid instanciate it as a var from your flow 
 */
public class TdMetroLazyDataModel extends GenericLazyDataModel<TdMetro> {
    private static final long serialVersionUID = 1L;

    @Inject
    transient private TdMetroRepository tdMetroRepository;
    @Inject
    transient private TdMetroSearchForm tdMetroSearchForm;

    List<TdMetro> datasource;

        @Override
        public TdMetro getRowData(String rowKey) {
            for(TdMetro tdMetro : datasource) {
                if(tdMetro.getMetroId().equals(rowKey))
                    return tdMetro;
            }

            return null;
        }

        @Override
        public Object getRowKey(TdMetro tdMetro)
        {
             return tdMetro.getMetroId();
        }

    /**
     * Prepare the search parameters and call the tdMetroRepository finder.
     * Automatically called by PrimeFaces component.
     */
    @Override
    public List<TdMetro> load(int first, int pageSize, String sortField, SortOrder sortOrder, Map<String, String> filters) {
        SearchParameters sp = tdMetroSearchForm.getSearchParameters();

        // ranges
        sp.clearRanges();
        sp.addRange(tdMetroSearchForm.getImportanceRange());
        sp.addRange(tdMetroSearchForm.getFlagRange());
        sp.addRange(tdMetroSearchForm.getUpdationDateRange());

        TdMetro tdMetro = tdMetroSearchForm.getTdMetro();
        setRowCount(tdMetroRepository.findCount(tdMetro, sp)); // total count so the paginator may display the total number of pages
        populateSearchParameters(sp, first, pageSize, sortField, sortOrder, filters); // load one page of data
        datasource = tdMetroRepository.find(tdMetro, sp);
        return datasource;
    }
}