/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/LazyDataModel.e.vm.java
 */
package com.app.mpadmin.web.domain;

import java.util.List;
import java.util.Map;
import javax.inject.Inject;

import org.primefaces.model.SortOrder;

import com.app.mpadmin.dao.support.SearchParameters;
import com.app.mpadmin.domain.TdPermission;
import com.app.mpadmin.repository.TdPermissionRepository;
import com.app.mpadmin.web.domain.support.GenericLazyDataModel;

/**
 * Provides server-side pagination for search.
 *
 * @see http://jira.springframework.org/browse/SWF-1224 to avoid instanciate it as a var from your flow 
 */
public class TdPermissionLazyDataModel extends GenericLazyDataModel<TdPermission> {
    private static final long serialVersionUID = 1L;

    @Inject
    transient private TdPermissionRepository tdPermissionRepository;
    @Inject
    transient private TdPermissionSearchForm tdPermissionSearchForm;

    List<TdPermission> datasource;

    @Override
    public TdPermission getRowData(String rowKey) {
        for(TdPermission tdPermission : datasource) {
            if(tdPermission.getPermissionId().equals(rowKey))
                return tdPermission;
        }

        return null;
    }

    @Override
    public Object getRowKey(TdPermission tdPermission)
    {
         return tdPermission.getPermissionId();
    }


    /**
     * Prepare the search parameters and call the tdPermissionRepository finder.
     * Automatically called by PrimeFaces component.
     */
    @Override
    public List<TdPermission> load(int first, int pageSize, String sortField, SortOrder sortOrder, Map<String, String> filters) {
        SearchParameters sp = tdPermissionSearchForm.getSearchParameters();

        // ranges
        sp.clearRanges();
        sp.addRange(tdPermissionSearchForm.getUpdationDateRange());

        TdPermission tdPermission = tdPermissionSearchForm.getTdPermission();
        setRowCount(tdPermissionRepository.findCount(tdPermission, sp)); // total count so the paginator may display the total number of pages
        populateSearchParameters(sp, first, pageSize, sortField, sortOrder, filters); // load one page of data
        datasource = tdPermissionRepository.find(tdPermission, sp);
        return datasource;
    }
}