/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/Controller.e.vm.java
 */
package com.app.mpadmin.web.domain;

import static com.app.mpadmin.web.util.PrimeFacesUtil.forceClose;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.app.mpadmin.domain.TdPermission;
import com.app.mpadmin.repository.TdPermissionRepository;
import com.app.mpadmin.web.converter.domain.TdPermissionConverter;
import com.app.mpadmin.web.util.MessageUtil;

/**
 * Thin controller layer allowing you to do business validation and other conditional 
 * checks that are easier to implement in Java than in webflow's xml syntax.
 */
@Named
@Singleton
public class TdPermissionController {
    private static final long serialVersionUID = 1L;

    @Inject
    private TdPermissionRepository tdPermissionRepository;

    @Inject
    private MessageUtil messageUtil;

    @Inject
    private TdPermissionConverter tdPermissionConverter;

    public TdPermission newIfNull(TdPermission tdPermission) {
        if (tdPermission != null) {
            return tdPermission;
        }

        return tdPermissionRepository.getNewWithDefaults();
    }

    public boolean save(TdPermission tdPermission) {
        tdPermissionRepository.save(tdPermission);
        messageUtil.info("status_saved_ok", tdPermissionConverter.print(tdPermission));
        return true;
    }

    public boolean saveAndClose(TdPermission tdPermission) {
        tdPermissionRepository.save(tdPermission);
        messageUtil.infoDelayed("status_saved_ok", tdPermissionConverter.print(tdPermission));
        forceClose();
        return true;
    }

    public boolean delete(TdPermission tdPermission) {
        String infoArg = tdPermissionConverter.print(tdPermission);
        tdPermissionRepository.delete(tdPermission);
        messageUtil.info("status_deleted_ok", infoArg);
        return true;
    }
}