/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/Controller.e.vm.java
 */
package com.app.mpadmin.web.domain;

import static com.app.mpadmin.web.util.PrimeFacesUtil.forceClose;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.app.mpadmin.domain.TdProduct;
import com.app.mpadmin.repository.TdProductRepository;
import com.app.mpadmin.web.converter.domain.TdProductConverter;
import com.app.mpadmin.web.util.MessageUtil;

/**
 * Thin controller layer allowing you to do business validation and other conditional 
 * checks that are easier to implement in Java than in webflow's xml syntax.
 */
@Named
@Singleton
public class TdProductController {
    private static final long serialVersionUID = 1L;

    @Inject
    private TdProductRepository tdProductRepository;

    @Inject
    private MessageUtil messageUtil;

    @Inject
    private TdProductConverter tdProductConverter;

    public TdProduct newIfNull(TdProduct tdProduct) {
        if (tdProduct != null) {
            return tdProduct;
        }

        return tdProductRepository.getNewWithDefaults();
    }

    public boolean save(TdProduct tdProduct) {
        tdProductRepository.save(tdProduct);
        messageUtil.info("status_saved_ok", tdProductConverter.print(tdProduct));
        return true;
    }

    public boolean saveAndClose(TdProduct tdProduct) {
        tdProductRepository.save(tdProduct);
        messageUtil.infoDelayed("status_saved_ok", tdProductConverter.print(tdProduct));
        forceClose();
        return true;
    }

    public boolean delete(TdProduct tdProduct) {
        String infoArg = tdProductConverter.print(tdProduct);
        tdProductRepository.delete(tdProduct);
        messageUtil.info("status_deleted_ok", infoArg);
        return true;
    }
}