/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/Controller.e.vm.java
 */
package com.app.mpadmin.web.domain;

import static com.app.mpadmin.web.util.PrimeFacesUtil.forceClose;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.app.mpadmin.domain.TdProductSubmodel;
import com.app.mpadmin.repository.TdProductSubmodelRepository;
import com.app.mpadmin.web.converter.domain.TdProductSubmodelConverter;
import com.app.mpadmin.web.util.MessageUtil;

/**
 * Thin controller layer allowing you to do business validation and other conditional 
 * checks that are easier to implement in Java than in webflow's xml syntax.
 */
@Named
@Singleton
public class TdProductSubmodelController {
    private static final long serialVersionUID = 1L;

    @Inject
    private TdProductSubmodelRepository tdProductSubmodelRepository;

    @Inject
    private MessageUtil messageUtil;

    @Inject
    private TdProductSubmodelConverter tdProductSubmodelConverter;

    public TdProductSubmodel newIfNull(TdProductSubmodel tdProductSubmodel) {
        if (tdProductSubmodel != null) {
            return tdProductSubmodel;
        }

        return tdProductSubmodelRepository.getNewWithDefaults();
    }

    public boolean save(TdProductSubmodel tdProductSubmodel) {
        tdProductSubmodelRepository.save(tdProductSubmodel);
        messageUtil.info("status_saved_ok", tdProductSubmodelConverter.print(tdProductSubmodel));
        return true;
    }

    public boolean saveAndClose(TdProductSubmodel tdProductSubmodel) {
        tdProductSubmodelRepository.save(tdProductSubmodel);
        messageUtil.infoDelayed("status_saved_ok", tdProductSubmodelConverter.print(tdProductSubmodel));
        forceClose();
        return true;
    }

    public boolean delete(TdProductSubmodel tdProductSubmodel) {
        String infoArg = tdProductSubmodelConverter.print(tdProductSubmodel);
        tdProductSubmodelRepository.delete(tdProductSubmodel);
        messageUtil.info("status_deleted_ok", infoArg);
        return true;
    }
}