/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/Controller.e.vm.java
 */
package com.app.mpadmin.web.domain;

import static com.app.mpadmin.web.util.PrimeFacesUtil.forceClose;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.app.mpadmin.domain.TdProductShipment;
import com.app.mpadmin.repository.TdProductShipmentRepository;
import com.app.mpadmin.web.converter.domain.TdProductShipmentConverter;
import com.app.mpadmin.web.util.MessageUtil;

/**
 * Thin controller layer allowing you to do business validation and other conditional 
 * checks that are easier to implement in Java than in webflow's xml syntax.
 */
@Named
@Singleton
public class TdProductShipmentController {
    private static final long serialVersionUID = 1L;

    @Inject
    private TdProductShipmentRepository tdProductShipmentRepository;

    @Inject
    private MessageUtil messageUtil;

    @Inject
    private TdProductShipmentConverter tdProductShipmentConverter;

    public TdProductShipment newIfNull(TdProductShipment tdProductShipment) {
        if (tdProductShipment != null) {
            return tdProductShipment;
        }

        return tdProductShipmentRepository.getNewWithDefaults();
    }

    public boolean save(TdProductShipment tdProductShipment) {
        tdProductShipmentRepository.save(tdProductShipment);
        messageUtil.info("status_saved_ok", tdProductShipmentConverter.print(tdProductShipment));
        return true;
    }

    public boolean saveAndClose(TdProductShipment tdProductShipment) {
        tdProductShipmentRepository.save(tdProductShipment);
        messageUtil.infoDelayed("status_saved_ok", tdProductShipmentConverter.print(tdProductShipment));
        forceClose();
        return true;
    }

    public boolean delete(TdProductShipment tdProductShipment) {
        String infoArg = tdProductShipmentConverter.print(tdProductShipment);
        tdProductShipmentRepository.delete(tdProductShipment);
        messageUtil.info("status_deleted_ok", infoArg);
        return true;
    }
}