/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/Controller.e.vm.java
 */
package com.app.mpadmin.web.domain;

import static com.app.mpadmin.web.util.PrimeFacesUtil.forceClose;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.app.mpadmin.domain.TdProductSupplier;
import com.app.mpadmin.repository.TdProductSupplierRepository;
import com.app.mpadmin.web.converter.domain.TdProductSupplierConverter;
import com.app.mpadmin.web.util.MessageUtil;

/**
 * Thin controller layer allowing you to do business validation and other conditional 
 * checks that are easier to implement in Java than in webflow's xml syntax.
 */
@Named
@Singleton
public class TdProductSupplierController {
    private static final long serialVersionUID = 1L;

    @Inject
    private TdProductSupplierRepository tdProductSupplierRepository;

    @Inject
    private MessageUtil messageUtil;

    @Inject
    private TdProductSupplierConverter tdProductSupplierConverter;

    public TdProductSupplier newIfNull(TdProductSupplier tdProductSupplier) {
        if (tdProductSupplier != null) {
            return tdProductSupplier;
        }

        return tdProductSupplierRepository.getNewWithDefaults();
    }

    public boolean save(TdProductSupplier tdProductSupplier) {
        tdProductSupplierRepository.save(tdProductSupplier);
        messageUtil.info("status_saved_ok", tdProductSupplierConverter.print(tdProductSupplier));
        return true;
    }

    public boolean saveAndClose(TdProductSupplier tdProductSupplier) {
        tdProductSupplierRepository.save(tdProductSupplier);
        messageUtil.infoDelayed("status_saved_ok", tdProductSupplierConverter.print(tdProductSupplier));
        forceClose();
        return true;
    }

    public boolean delete(TdProductSupplier tdProductSupplier) {
        String infoArg = tdProductSupplierConverter.print(tdProductSupplier);
        tdProductSupplierRepository.delete(tdProductSupplier);
        messageUtil.info("status_deleted_ok", infoArg);
        return true;
    }
}