/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/SearchForm.e.vm.java
 */
package com.app.mpadmin.web.domain;

import static com.app.mpadmin.dao.support.EntitySelectors.TdMakeModelSelector.newTdMakeModelSelector;
import static com.app.mpadmin.dao.support.EntitySelectors.TdProductSelector.newTdProductSelector;
import static com.app.mpadmin.dao.support.Ranges.RangeInteger.newRangeInteger;
import static com.app.mpadmin.domain.TdProductModel_.makeModelId;
import static com.app.mpadmin.domain.TdProductModel_.productId;
import static com.app.mpadmin.domain.TdProductModel_.productModelId;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;


import com.app.mpadmin.dao.support.EntitySelectors.TdProductSelector;
import com.app.mpadmin.dao.support.EntitySelectors.TdMakeModelSelector;
import com.app.mpadmin.dao.support.Ranges.RangeInteger;
import com.app.mpadmin.domain.TdProductModel;
import com.app.mpadmin.web.domain.support.SearchFormBase;

/**
 * Simple parameters holder for tdProductModel search.
 */
@Component
@Scope("session")
public class TdProductModelSearchForm extends SearchFormBase {
    private static final long serialVersionUID = 1L;

    private TdProductModel tdProductModel = new TdProductModel();
    private TdMakeModelSelector<TdProductModel> makeModelSelector = newTdMakeModelSelector(makeModelId);
    private TdProductSelector<TdProductModel> productSelector = newTdProductSelector(productId);
    //private RangeInteger<TdProductModel> makeModelIdRange = newRangeInteger(makeModelId);
    //private RangeInteger<TdProductModel> productIdRange = newRangeInteger(productId);
    private RangeInteger<TdProductModel> productModelIdRange = newRangeInteger(productModelId);

    public TdProductModel getTdProductModel() {
        return tdProductModel;
    }
    
    
 // Selectors for x-to-one associations
    public TdMakeModelSelector<TdProductModel> getMakeModelSelector() {
        return makeModelSelector;
    }
    
    public TdProductSelector<TdProductModel> getProductSelector() {
        return productSelector;
    }

    public RangeInteger<TdProductModel> getProductModelIdRange() {
        return productModelIdRange;
    }

    // Ranges, used from the view.
   /* public RangeInteger<TdProductModel> getMakeModelIdRange() {
        return makeModelIdRange;
    }

    public RangeInteger<TdProductModel> getProductIdRange() {
        return productIdRange;
    }*/
}