/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/Controller.e.vm.java
 */
package com.app.mpadmin.web.domain;

import static com.app.mpadmin.web.util.PrimeFacesUtil.forceClose;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.app.mpadmin.domain.TdRole;
import com.app.mpadmin.repository.TdRoleRepository;
import com.app.mpadmin.web.converter.domain.TdRoleConverter;
import com.app.mpadmin.web.util.MessageUtil;

/**
 * Thin controller layer allowing you to do business validation and other conditional 
 * checks that are easier to implement in Java than in webflow's xml syntax.
 */
@Named
@Singleton
public class TdRoleController {
    private static final long serialVersionUID = 1L;

    @Inject
    private TdRoleRepository tdRoleRepository;

    @Inject
    private MessageUtil messageUtil;

    @Inject
    private TdRoleConverter tdRoleConverter;

    public TdRole newIfNull(TdRole tdRole) {
        if (tdRole != null) {
            return tdRole;
        }

        return tdRoleRepository.getNewWithDefaults();
    }

    public boolean save(TdRole tdRole) {
        tdRoleRepository.save(tdRole);
        messageUtil.info("status_saved_ok", tdRoleConverter.print(tdRole));
        return true;
    }

    public boolean saveAndClose(TdRole tdRole) {
        tdRoleRepository.save(tdRole);
        messageUtil.infoDelayed("status_saved_ok", tdRoleConverter.print(tdRole));
        forceClose();
        return true;
    }

    public boolean delete(TdRole tdRole) {
        String infoArg = tdRoleConverter.print(tdRole);
        tdRoleRepository.delete(tdRole);
        messageUtil.info("status_deleted_ok", infoArg);
        return true;
    }
}