/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/SearchForm.e.vm.java
 */
package com.app.mpadmin.web.domain;

import static com.app.mpadmin.dao.support.EntitySelectors.TdCountrySelector.newTdCountrySelector;
import static com.app.mpadmin.dao.support.Ranges.RangeDate.newRangeDate;
import static com.app.mpadmin.dao.support.Ranges.RangeInteger.newRangeInteger;
import static com.app.mpadmin.domain.TdState_.*;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import com.app.mpadmin.dao.support.EntitySelectors.TdCountrySelector;
import com.app.mpadmin.dao.support.Ranges.RangeDate;
import com.app.mpadmin.dao.support.Ranges.RangeInteger;
import com.app.mpadmin.domain.TdState;
import com.app.mpadmin.web.domain.support.SearchFormBase;

/**
 * Simple parameters holder for tdState search.
 */
@Component
@Scope("request")
public class TdStateSearchForm extends SearchFormBase {
    private static final long serialVersionUID = 1L;

    private TdState tdState = new TdState();
    private RangeInteger<TdState> importanceRange = newRangeInteger(importance);
    private RangeDate<TdState> updationDateRange = newRangeDate(updationDate);
    private TdCountrySelector<TdState> countrySelector = newTdCountrySelector(countryId);
    private RangeInteger<TdState> stateIdRange = newRangeInteger(stateId);

    public TdState getTdState() {
        return tdState;
    }

    // Ranges, used from the view.
    public RangeInteger<TdState> getStateIdRange(){
        return stateIdRange;
    }
    public RangeInteger<TdState> getImportanceRange() {
        return importanceRange;
    }

    public RangeDate<TdState> getUpdationDateRange() {
        return updationDateRange;
    }

    // Selectors for x-to-one associations
    public TdCountrySelector<TdState> getCountrySelector() {
        return countrySelector;
    }
}