/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/Controller.e.vm.java
 */
package com.app.mpadmin.web.domain;

import static com.app.mpadmin.web.util.PrimeFacesUtil.forceClose;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.app.mpadmin.domain.TdState;
import com.app.mpadmin.repository.TdStateRepository;
import com.app.mpadmin.web.converter.domain.TdStateConverter;
import com.app.mpadmin.web.util.MessageUtil;

/**
 * Thin controller layer allowing you to do business validation and other conditional 
 * checks that are easier to implement in Java than in webflow's xml syntax.
 */
@Named
@Singleton
public class TdStateController {
    private static final long serialVersionUID = 1L;

    @Inject
    private TdStateRepository tdStateRepository;

    @Inject
    private MessageUtil messageUtil;

    @Inject
    private TdStateConverter tdStateConverter;

    public TdState newIfNull(TdState tdState) {
        if (tdState != null) {
            return tdState;
        }

        return tdStateRepository.getNewWithDefaults();
    }

    public boolean save(TdState tdState) {
        tdStateRepository.save(tdState);
        messageUtil.info("status_saved_ok", tdStateConverter.print(tdState));
        return true;
    }

    public boolean saveAndClose(TdState tdState) {
        tdStateRepository.save(tdState);
        messageUtil.infoDelayed("status_saved_ok", tdStateConverter.print(tdState));
        forceClose();
        return true;
    }

    public boolean delete(TdState tdState) {
        String infoArg = tdStateConverter.print(tdState);
        tdStateRepository.delete(tdState);
        messageUtil.info("status_deleted_ok", infoArg);
        return true;
    }
}