/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/LazyDataModel.e.vm.java
 */
package com.app.mpadmin.web.domain;

import java.util.List;
import java.util.Map;
import javax.inject.Inject;

import org.primefaces.model.SortOrder;

import com.app.mpadmin.dao.support.SearchParameters;
import com.app.mpadmin.domain.TdUserDetail;
import com.app.mpadmin.repository.TdUserDetailRepository;
import com.app.mpadmin.web.domain.support.GenericLazyDataModel;

/**
 * Provides server-side pagination for search.
 *
 * @see http://jira.springframework.org/browse/SWF-1224 to avoid instanciate it as a var from your flow 
 */
public class TdUserDetailLazyDataModel extends GenericLazyDataModel<TdUserDetail> {
    private static final long serialVersionUID = 1L;

    @Inject
    transient private TdUserDetailRepository tdUserDetailRepository;
    @Inject
    transient private TdUserDetailSearchForm tdUserDetailSearchForm;

    /**
     * Prepare the search parameters and call the tdUserDetailRepository finder.
     * Automatically called by PrimeFaces component.
     */
    @Override
    public List<TdUserDetail> load(int first, int pageSize, String sortField, SortOrder sortOrder, Map<String, String> filters) {
        SearchParameters sp = tdUserDetailSearchForm.getSearchParameters();

        // ranges
        sp.clearRanges();
        sp.addRange(tdUserDetailSearchForm.getIsActiveRange());
        sp.addRange(tdUserDetailSearchForm.getDobRange());
        sp.addRange(tdUserDetailSearchForm.getPhoneRange());
        sp.addRange(tdUserDetailSearchForm.getUpdationDateRange());
        sp.addRange(tdUserDetailSearchForm.getCreditRange());

        // entity selectors
        sp.clearEntitySelectors();
        sp.addEntitySelector(tdUserDetailSearchForm.getUserSelector());

        TdUserDetail tdUserDetail = tdUserDetailSearchForm.getTdUserDetail();
        setRowCount(tdUserDetailRepository.findCount(tdUserDetail, sp)); // total count so the paginator may display the total number of pages
        populateSearchParameters(sp, first, pageSize, sortField, sortOrder, filters); // load one page of data

        return tdUserDetailRepository.find(tdUserDetail, sp);
    }
}