/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/LazyDataModel.e.vm.java
 */
package com.app.mpadmin.web.domain;

import java.util.List;
import java.util.Map;
import javax.inject.Inject;

import org.primefaces.model.SortOrder;

import com.app.mpadmin.dao.support.SearchParameters;
import com.app.mpadmin.domain.TdUserAuth;
import com.app.mpadmin.repository.TdUserAuthRepository;
import com.app.mpadmin.web.domain.support.GenericLazyDataModel;

/**
 * Provides server-side pagination for search.
 *
 * @see http://jira.springframework.org/browse/SWF-1224 to avoid instanciate it as a var from your flow 
 */
public class TdUserAuthLazyDataModel extends GenericLazyDataModel<TdUserAuth> {
    private static final long serialVersionUID = 1L;

    @Inject
    transient private TdUserAuthRepository tdUserAuthRepository;
    @Inject
    transient private TdUserAuthSearchForm tdUserAuthSearchForm;

    List<TdUserAuth> datasource;

    @Override
    public TdUserAuth getRowData(String rowKey) {
        for(TdUserAuth tdUserAuth : datasource) {
            if(tdUserAuth.getUserId().equals(rowKey))
                return tdUserAuth;
        }

        return null;
    }

    @Override
    public Object getRowKey(TdUserAuth tdUserAuth)
    {
         return tdUserAuth.getUserId();
    }


    /**
     * Prepare the search parameters and call the tdUserAuthRepository finder.
     * Automatically called by PrimeFaces component.
     */
    @Override
    public List<TdUserAuth> load(int first, int pageSize, String sortField, SortOrder sortOrder, Map<String, String> filters) {
        SearchParameters sp = tdUserAuthSearchForm.getSearchParameters();

        // ranges
        sp.clearRanges();
        sp.addRange(tdUserAuthSearchForm.getIsActiveRange());
        sp.addRange(tdUserAuthSearchForm.getUpdationDateRange());
        sp.addRange(tdUserAuthSearchForm.getUserIdRange());
        // entity selectors
        sp.clearEntitySelectors();
        sp.addEntitySelector(tdUserAuthSearchForm.getRoleSelector());

        TdUserAuth tdUserAuth = tdUserAuthSearchForm.getTdUserAuth();
        setRowCount(tdUserAuthRepository.findCount(tdUserAuth, sp)); // total count so the paginator may display the total number of pages
        populateSearchParameters(sp, first, pageSize, sortField, sortOrder, filters); // load one page of data
        datasource = tdUserAuthRepository.find(tdUserAuth, sp);
        return datasource;
    }
}