/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/Controller.e.vm.java
 */
package com.app.mpadmin.web.domain;

import static com.app.mpadmin.web.util.PrimeFacesUtil.forceClose;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.app.mpadmin.domain.TdUserAuth;
import com.app.mpadmin.repository.TdUserAuthRepository;
import com.app.mpadmin.web.converter.domain.TdUserAuthConverter;
import com.app.mpadmin.web.util.MessageUtil;

/**
 * Thin controller layer allowing you to do business validation and other conditional 
 * checks that are easier to implement in Java than in webflow's xml syntax.
 */
@Named
@Singleton
public class TdUserAuthController {
    private static final long serialVersionUID = 1L;

    @Inject
    private TdUserAuthRepository tdUserAuthRepository;

    @Inject
    private MessageUtil messageUtil;

    @Inject
    private TdUserAuthConverter tdUserAuthConverter;

    public TdUserAuth newIfNull(TdUserAuth tdUserAuth) {
        if (tdUserAuth != null) {
            return tdUserAuth;
        }

        return tdUserAuthRepository.getNewWithDefaults();
    }

    public boolean save(TdUserAuth tdUserAuth) {
        tdUserAuthRepository.save(tdUserAuth);
        messageUtil.info("status_saved_ok", tdUserAuthConverter.print(tdUserAuth));
        return true;
    }

    public boolean saveAndClose(TdUserAuth tdUserAuth) {
        tdUserAuthRepository.save(tdUserAuth);
        messageUtil.infoDelayed("status_saved_ok", tdUserAuthConverter.print(tdUserAuth));
        forceClose();
        return true;
    }

    public boolean delete(TdUserAuth tdUserAuth) {
        String infoArg = tdUserAuthConverter.print(tdUserAuth);
        tdUserAuthRepository.delete(tdUserAuth);
        messageUtil.info("status_deleted_ok", infoArg);
        return true;
    }
}