/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/Controller.e.vm.java
 */
package com.app.mpadmin.web.domain;

import static com.app.mpadmin.web.util.PrimeFacesUtil.forceClose;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.app.mpadmin.domain.TdVote;
import com.app.mpadmin.repository.TdVoteRepository;
import com.app.mpadmin.web.converter.domain.TdVoteConverter;
import com.app.mpadmin.web.util.MessageUtil;

/**
 * Thin controller layer allowing you to do business validation and other conditional 
 * checks that are easier to implement in Java than in webflow's xml syntax.
 */
@Named
@Singleton
public class TdVoteController {
    private static final long serialVersionUID = 1L;

    @Inject
    private TdVoteRepository tdVoteRepository;

    @Inject
    private MessageUtil messageUtil;

    @Inject
    private TdVoteConverter tdVoteConverter;

    public TdVote newIfNull(TdVote tdVote) {
        if (tdVote != null) {
            return tdVote;
        }

        return tdVoteRepository.getNewWithDefaults();
    }

    public boolean save(TdVote tdVote) {
        tdVoteRepository.save(tdVote);
        messageUtil.info("status_saved_ok", tdVoteConverter.print(tdVote));
        return true;
    }

    public boolean saveAndClose(TdVote tdVote) {
        tdVoteRepository.save(tdVote);
        messageUtil.infoDelayed("status_saved_ok", tdVoteConverter.print(tdVote));
        forceClose();
        return true;
    }

    public boolean delete(TdVote tdVote) {
        String infoArg = tdVoteConverter.print(tdVote);
        tdVoteRepository.delete(tdVote);
        messageUtil.info("status_deleted_ok", infoArg);
        return true;
    }
}